global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'desa-cilame-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Frontend Next.js application
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Main Database Server
  - job_name: 'main-db-server'
    static_configs:
      - targets: ['main-db-server:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # UMKM Database Server
  - job_name: 'umkm-db-server'
    static_configs:
      - targets: ['umkm-db-server:5001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Admin Database Server
  - job_name: 'admin-db-server'
    static_configs:
      - targets: ['admin-db-server:5002']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Location Database Server
  - job_name: 'location-db-server'
    static_configs:
      - targets: ['location-db-server:5003']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MySQL Database
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Custom application metrics
  - job_name: 'desa-cilame-app'
    static_configs:
      - targets: 
        - 'frontend:3000'
        - 'main-db-server:5000'
        - 'umkm-db-server:5001'
        - 'admin-db-server:5002'
        - 'location-db-server:5003'
    metrics_path: '/api/health'
    scrape_interval: 60s
    scrape_timeout: 15s
    params:
      format: ['prometheus']

  # Blackbox exporter for external monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://your-domain.com
        - https://your-domain.com/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115