'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'id' | 'su';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Definisi tipe untuk objek terjemahan
type TranslationObject = {
  [key: string]: string;
};

type Translations = {
  [K in Language]: TranslationObject;
};

const translations: Translations = {
  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.village_profile': 'Profil Desa',
    'nav.about_village': 'Tentang Desa',
    'nav.village_history': 'Sejarah Desa',
    'nav.vision_mission': 'Visi & Misi',
    'nav.organization_structure': 'Struktur Organisasi',
    'nav.village_potential': 'Potensi Desa',
    'nav.information': 'Informasi',
    'nav.village_news': 'Berita Desa',
    'nav.announcements': 'Pengumuman',
    'nav.service_schedule': 'Jadwal Pelayanan',
    'nav.public_documents': 'Dokumen Publik',
    'nav.services_economy': 'Layanan & Ekonomi',
    'nav.local_job_market': 'Pasar Kerja Lokal',
    'nav.village_umkm': 'UMKM Desa',
    'nav.village_online_store': 'Toko Online Desa',
    'nav.transparency': 'Transparansi',
    'nav.village_budget': 'APBDes (Grafik & Rincian)',
    'nav.activity_reports': 'Laporan Kegiatan',
    'nav.contact_complaints': 'Kontak & Aduan',
    'nav.contact_form': 'Form Kontak',
    'nav.citizen_reports': 'Laporan Warga',
    'nav.location_map': 'Lokasi & Peta Desa',
    'nav.search_placeholder': 'Cari informasi...',
    'nav.online_letter_request': 'Ajukan Surat Online',
    'nav.job_market': 'Pasar Kerja',
    'nav.umkm': 'UMKM',
    'nav.village_regulations': 'Peraturan Desa',
    'nav.contact': 'Kontak',
    'nav.login': 'Login',
    
    // Hero Section
    'hero.welcome': 'Selamat Datang di Desa Cilame',
    'hero.subtitle': 'Portal Digital untuk Pelayanan Masyarakat yang Lebih Baik',
    'hero.transparency': 'Transparansi dan Akuntabilitas',
    'hero.transparency_subtitle': 'Keterbukaan Informasi untuk Kepercayaan Masyarakat',
    'hero.umkm': 'Pemberdayaan UMKM Desa',
    'hero.umkm_subtitle': 'Mendukung Ekonomi Lokal dan Kesejahteraan Masyarakat',
    'hero.online_services': 'Layanan Online',
    'hero.contact_us': 'Hubungi Kami',
    
    // Quick Access
    'quick.title': 'Akses Cepat Layanan',
    'quick.subtitle': 'Pilih layanan yang Anda butuhkan untuk menghemat waktu dan tenaga',
    'quick.online_letter': 'Surat Online',
    'quick.online_letter_desc': 'Buat surat keterangan dengan mudah',
    'quick.village_umkm': 'UMKM Desa',
    'quick.village_umkm_desc': 'Jelajahi produk lokal desa',
    'quick.citizen_report': 'Laporan Warga',
    'quick.citizen_report_desc': 'Sampaikan keluhan dan aspirasi',
    'quick.social_aid': 'Info Bansos',
    'quick.social_aid_desc': 'Informasi bantuan sosial terkini',
    'quick.job_market': 'Pasar Kerja',
    'quick.job_market_desc': 'Cari jasa dan pekerja lokal',
    'quick.population': 'Daftar Penduduk',
    'quick.population_desc': 'Update data kependudukan',
    'quick.transparency': 'Transparansi',
    'quick.transparency_desc': 'Laporan keuangan desa',
    'quick.payment': 'Pembayaran',
    'quick.payment_desc': 'Bayar retribusi dan pajak',
    
    // Stats Section
    'stats.title': 'Data Desa Cilame',
    'stats.subtitle': 'Informasi statistik terkini tentang kondisi demografis dan ekonomi desa',
    'stats.total_population': 'Total Penduduk',
    'stats.population_subtitle': 'Jiwa terdaftar',
    'stats.family_heads': 'Kepala Keluarga',
    'stats.family_subtitle': 'KK aktif',
    'stats.active_umkm': 'UMKM Aktif',
    'stats.umkm_subtitle': 'Usaha lokal',
    'stats.growth': 'Pertumbuhan',
    'stats.growth_subtitle': 'Ekonomi tahun ini',
    
    // News Section
    'news.title': 'Berita Terkini',
    'news.subtitle': 'Ikuti perkembangan terbaru dari Desa Cilame',
    'news.view_all': 'Lihat Semua Berita',
    'news.read_more': 'Baca Selengkapnya',
    
    // Services
    'services.title': 'Layanan Digital Desa Cilame',
    'services.subtitle': 'Nikmati berbagai layanan digital yang memudahkan kehidupan masyarakat desa',
    'services.information_portal': 'Portal Informasi',
    'services.information_desc': 'Berita, pengumuman, dan jadwal layanan',
    'services.job_market': 'Pasar Tenaga Kerja',
    'services.job_market_desc': 'Cari jasa dan pekerja lokal',
    'services.umkm_directory': 'Direktori UMKM',
    'services.umkm_desc': 'Toko online untuk produk lokal',
    'services.financial_transparency': 'Transparansi Keuangan',
    'services.financial_desc': 'Laporan APBDes dan realisasi',
    
    // Contact Section
    'contact.title': 'Hubungi Desa Cilame',
    'contact.subtitle': 'Kami siap melayani Anda dengan sepenuh hati. Jangan ragu untuk menghubungi kami untuk berbagai keperluan administrasi dan layanan desa.',
    'contact.service_hours_title': 'JAM PELAYANAN DESA CILAME',
    'contact.service_days_title': 'Hari & Waktu Layanan',
    'contact.monday_thursday': 'Senin – Kamis',
    'contact.friday': 'Jumat',
    'contact.weekend_holiday': 'Sabtu – Minggu & Hari Libur Nasional',
    'contact.closed': 'Tutup',
    'contact.break_hours_title': 'Jam Istirahat',
    'contact.notes_title': 'Catatan',
    'contact.note_1': 'Datang lebih awal untuk menghindari antrean.',
    'contact.note_2': 'Pastikan semua dokumen persyaratan sudah lengkap sebelum mengajukan pelayanan.',
    'contact.quick_message': 'Pesan Cepat',
    'contact.full_name': 'Nama Lengkap',
    'contact.email': 'Email',
    'contact.message': 'Pesan Anda',
    'contact.send_message': 'Kirim Pesan',
    'contact.office_hours': 'Senin - Kamis: 08.00 - 16.00 | Jumat: 08.00 - 11.30 | Sabtu - Minggu dan Libur Nasional: Tutup',
    
    // Footer
    'footer.description': 'Portal digital resmi Desa Cilame untuk melayani masyarakat dengan teknologi modern.',
    'footer.services': 'Layanan',
    'footer.help': 'Bantuan',
    'footer.guide': 'Panduan',
    'footer.faq': 'FAQ',
    'footer.follow_us': 'Ikuti Kami',
    'footer.copyright': '© 2025 Desa Cilame. Semua hak cipta dilindungi.',
    
    // Chatbot
    'chatbot.title': 'Asisten Desa Cilame',
    'chatbot.status': 'Online • Siap membantu Anda',
    'chatbot.greeting': 'Halo! Saya Asisten Virtual Desa Cilame. Ada yang bisa saya bantu?',
    'chatbot.quick_questions': 'Pertanyaan umum:',
    'chatbot.letter_guide': 'Cara membuat surat keterangan',
    'chatbot.social_aid_info': 'Info bantuan sosial',
    'chatbot.service_schedule': 'Jadwal pelayanan',
    'chatbot.village_contact': 'Kontak desa',
    'chatbot.whatsapp': 'Chat via WhatsApp',
    'chatbot.type_message': 'Ketik pesan...',
    'chatbot.response': 'Terima kasih atas pertanyaan Anda. Tim kami akan segera membantu Anda.',
    
    // Announcements
    'announcement.social_aid': '🔔 Pendaftaran Bantuan Sosial PKH Tahap II dibuka hingga 31 Januari 2025',
    'announcement.online_service': '📋 Pelayanan Surat Keterangan Online kini tersedia 24/7',
    'announcement.market': '🏪 Pasar Rakyat Desa Cilame buka setiap Selasa dan Jumat',
    'announcement.budget_report': '💰 Laporan APBDes Triwulan IV telah dipublikasikan',
    'announcement.latest': 'Terbaru',
    
    // Information Page
    'info.title': 'Portal Informasi Desa',
    'info.subtitle': 'Akses informasi terkini, pengumuman resmi, jadwal layanan, dan dokumen publik Desa Cilame',
    'info.search_placeholder': 'Cari berita, pengumuman, atau dokumen...',
    'info.all_categories': 'Semua',
    'info.announcements': 'Pengumuman',
    'info.news': 'Berita',
    'info.service_schedule': 'Jadwal Layanan',
    'info.public_documents': 'Dokumen Publik',
    'info.latest_info': 'Informasi Terbaru',
    'info.service_schedule_title': 'Jadwal Layanan',
    'info.public_documents_title': 'Dokumen Publik',
    'info.emergency_contact': 'Kontak Darurat',
    'info.police': 'Polsek: 110',
    'info.fire_dept': 'Pemadam: 113',
    'info.ambulance': 'Ambulans: 118',
    'info.village_office': 'Desa',
    'info.download': 'Unduh',
    'info.no_results': 'Tidak ada informasi yang ditemukan',
    
    // Job Market Page
    'job.title': 'Pasar Tenaga Kerja Lokal',
    'job.subtitle': 'Temukan jasa dan pekerja terpercaya di Desa Cilame dengan sistem booking dan pembayaran yang aman',
    'job.search_placeholder': 'Cari pekerja, jasa, atau keahlian...',
    'job.all_categories': 'Semua Kategori',
    'job.construction': 'Tukang & Konstruksi',
    'job.housekeeping': 'Pembantu Rumah Tangga',
    'job.agriculture': 'Pertanian & Kebun',
    'job.automotive': 'Otomotif',
    'job.electronics': 'Service Elektronik',
    'job.culinary': 'Jasa Kuliner',
    'job.others': 'Lainnya',
    'job.all_locations': 'Semua Lokasi',
    'job.center': 'Pusat Desa',
    'job.north': 'Cilame Utara',
    'job.south': 'Cilame Selatan',
    'job.east': 'Cilame Timur',
    'job.west': 'Cilame Barat',
    'job.showing_workers': 'Menampilkan {count} pekerja tersedia',
    'job.per_hour': 'per jam',
    'job.completed_jobs': 'pekerjaan selesai',
    'job.booking': 'Booking',
    'job.available': 'Tersedia',
    'job.busy_until': 'Sibuk hingga Minggu',
    'job.no_workers': 'Tidak ada pekerja yang sesuai dengan pencarian Anda',
    'job.join_worker': 'Ingin Bergabung Sebagai Pekerja?',
    'job.join_description': 'Daftarkan keahlian Anda dan dapatkan penghasilan tambahan dari jasa yang Anda tawarkan',
    'job.register_worker': 'Daftar Sebagai Pekerja',
    
    // UMKM Page
    'umkm.title': 'Direktori UMKM Desa Cilame',
    'umkm.subtitle': 'Temukan dan dukung produk lokal berkualitas dari usaha mikro, kecil, dan menengah di Desa Cilame',
    'umkm.search_placeholder': 'Cari UMKM, produk, atau layanan...',
    'umkm.all_categories': 'Semua Kategori',
    'umkm.culinary': 'Kuliner',
    'umkm.fashion': 'Fashion & Aksesoris',
    'umkm.handicraft': 'Kerajinan Tangan',
    'umkm.agriculture': 'Produk Pertanian',
    'umkm.services': 'Jasa & Layanan',
    'umkm.electronics': 'Elektronik',
    'umkm.beauty': 'Kecantikan & Kesehatan',
    'umkm.Kuliner': 'Kuliner',
    'umkm.kuliner': 'Kuliner',
    'umkm.Kerajinan': 'Kerajinan Tangan',
    'umkm.kerajinan': 'Kerajinan Tangan',
    'umkm.Pertanian': 'Produk Pertanian',
    'umkm.pertanian': 'Produk Pertanian',
    'umkm.Kosmetik': 'Kecantikan & Kosmetik',
    'umkm.kosmetik': 'Kecantikan & Kosmetik',
    'umkm.Retail': 'Retail',
    'umkm.retail': 'Retail',
    'umkm.Tekstil': 'Tekstil',
    'umkm.tekstil': 'Tekstil',
    'umkm.Meubelair': 'Meubelair',
    'umkm.meubelair': 'Meubelair',
    'umkm.Fashion': 'Fashion & Aksesoris',
    'umkm.Jasa': 'Jasa & Layanan',
    'umkm.jasa': 'Jasa & Layanan',
    'umkm.Elektronik': 'Elektronik',
    'umkm.elektronik': 'Elektronik',
    'umkm.employees': 'Karyawan',
    'umkm.featured': 'UMKM Unggulan',
    'umkm.all_umkm': 'Semua UMKM',
    'umkm.category': 'Kategori',
    'umkm.showing_all': 'Menampilkan semua UMKM',
    'umkm.popular_products': 'Produk Populer:',
    'umkm.view_store': 'Lihat Toko',
    'umkm.contact': 'Hubungi',
    'umkm.products_available': 'produk tersedia',
    'umkm.no_results': 'Tidak ada UMKM yang sesuai dengan pencarian Anda',
    'umkm.register_business': 'Ingin Mendaftarkan Usaha Anda?',
    'umkm.register_description': 'Bergabunglah dengan direktori UMKM Desa Cilame dan jangkau lebih banyak pelanggan',
    'umkm.register_umkm': 'Daftar UMKM',
    'umkm.try_different_search': 'Coba ubah kata kunci pencarian atau filter kategori',
    'umkm.register_title': 'Daftarkan UMKM Anda',
    'umkm.register_subtitle': 'Bergabunglah dengan direktori UMKM Desa Cilame dan jangkau lebih banyak pelanggan',
    'umkm.register_now': 'Daftar Sekarang',
    
    // UMKM Detail Page
    'common.back': 'Kembali',
    'umkm.store_not_found': 'UMKM Tidak Ditemukan',
    'umkm.back_to_list': 'Kembali ke Daftar UMKM',
    'umkm.contact_store': 'Hubungi Toko',
    'umkm.call_now': 'Telepon Sekarang',
    'umkm.chat_whatsapp': 'Chat WhatsApp',
    'umkm.view_location': 'Lihat Lokasi',
    'umkm.store_stats': 'Statistik Toko',
    'umkm.rating': 'Rating',
    'umkm.total_reviews': 'Total Ulasan',
    'umkm.products': 'Produk',
    'umkm.established_year': 'Tahun Berdiri',
    'umkm.similar_stores': 'Toko Serupa',
    'umkm.view_all_umkm': 'Lihat Semua UMKM',
    'umkm.specialties': 'Spesialisasi',
    'umkm.featured_products': 'Produk Unggulan',
    'umkm.order': 'Pesan',
    'umkm.since': 'Sejak',
    'umkm.owner': 'Pemilik',
    'umkm.reviews': 'ulasan',
    
    // Transparency Page
    'transparency.title': 'Transparansi Keuangan Desa',
    'transparency.subtitle': 'Keterbukaan informasi keuangan dan pelaksanaan program pembangunan untuk kepercayaan masyarakat',
    'transparency.year': 'Tahun:',
    'transparency.period': 'Periode:',
    'transparency.annual': 'Tahunan',
    'transparency.quarter_4': 'Triwulan IV',
    'transparency.quarter_3': 'Triwulan III',
    'transparency.quarter_2': 'Triwulan II',
    'transparency.quarter_1': 'Triwulan I',
    'transparency.total_budget': 'Total Anggaran',
    'transparency.income_realization': 'Realisasi Pendapatan',
    'transparency.expense_realization': 'Realisasi Belanja',
    'transparency.remaining_budget': 'Sisa Anggaran',
    'transparency.income_breakdown': 'Rincian Pendapatan',
    'transparency.expense_breakdown': 'Rincian Belanja',
    'transparency.program_progress': 'Progress Program Pembangunan',
    'transparency.financial_reports': 'Laporan Keuangan',
    'transparency.completed': 'Selesai',
    'transparency.ongoing': 'Berlangsung',
    'transparency.program_completed': 'Program telah selesai dilaksanakan',
    'transparency.program_ongoing': 'Program sedang dalam tahap pelaksanaan',
    'transparency.need_more_info': 'Butuh Informasi Lebih Lanjut?',
    'transparency.contact_finance': 'Hubungi Bagian Keuangan Desa untuk penjelasan detail mengenai laporan keuangan',
    'transparency.ask_question': 'Ajukan Pertanyaan',
    'transparency.schedule_consultation': 'Jadwalkan Konsultasi',
    'transparency.downloads': 'unduhan',
    
    // UI Elements
    'ui.grid': 'Grid',
    'ui.list': 'List',
    
    // Regulations Page
    'regulations.title': 'Peraturan Desa',
    'regulations.subtitle': 'Kumpulan peraturan desa yang berlaku di wilayah Kabupaten Bandung Barat',
    'regulations.search_placeholder': 'Cari peraturan desa...',
    'regulations.all_years': 'Semua Tahun',
    'regulations.download_count': 'kali diunduh',
    'regulations.no_results': 'Tidak ada peraturan yang ditemukan',
    'regulations.download_button': 'Unduh',
    'regulations.showing_results': 'Menampilkan {count} peraturan',
    'regulations.category_peraturan': 'Peraturan',
  },
  su: {
    // Navigation
    'nav.home': 'Tepas',
    'nav.village_profile': 'Profil Désa',
    'nav.about_village': 'Ngeunaan Désa',
    'nav.village_history': 'Sajarah Désa',
    'nav.vision_mission': 'Visi & Misi',
    'nav.organization_structure': 'Struktur Organisasi',
    'nav.village_potential': 'Poténsi Désa',
    'nav.information': 'Informasi',
    'nav.village_news': 'Béja Désa',
    'nav.announcements': 'Pangumuman',
    'nav.service_schedule': 'Jadwal Palayanan',
    'nav.public_documents': 'Dokumén Umum',
    'nav.services_economy': 'Palayanan & Ékonomi',
    'nav.local_job_market': 'Pasar Pagawéan Lokal',
    'nav.village_umkm': 'UMKM Désa',
    'nav.village_online_store': 'Toko Online Désa',
    'nav.transparency': 'Transparansi',
    'nav.village_budget': 'APBDes (Grafik & Rincian)',
    'nav.activity_reports': 'Laporan Kagiatan',
    'nav.contact_complaints': 'Kontak & Aduan',
    'nav.contact_form': 'Form Kontak',
    'nav.citizen_reports': 'Laporan Warga',
    'nav.location_map': 'Lokasi & Peta Désa',
    'nav.search_placeholder': 'Milarian inpormasi...',
    'nav.online_letter_request': 'Ajukeun Surat Online',
    'nav.job_market': 'Pasar Pagawéan',
    'nav.umkm': 'UMKM',
    'nav.village_regulations': 'Aturan Desa',
    'nav.contact': 'Kontak',
    'nav.login': 'Lebet',
    
    // Hero Section
    'hero.welcome': 'Wilujeng Sumping ka Désa Cilame',
    'hero.subtitle': 'Portal Digital pikeun Palayanan Masarakat anu Langkung Saé',
    'hero.transparency': 'Transparansi sareng Akuntabilitas',
    'hero.transparency_subtitle': 'Kabuka Informasi pikeun Kapercayaan Masarakat',
    'hero.umkm': 'Pemberdayaan UMKM Désa',
    'hero.umkm_subtitle': 'Ngadukung Ékonomi Lokal jeung Kasejahteraan Masarakat',
    'hero.online_services': 'Palayanan Online',
    'hero.contact_us': 'Kontak Kami',
    
    // Quick Access
    'quick.title': 'Aksés Gancang Palayanan',
    'quick.subtitle': 'Pilih palayanan anu anjeun peryogikeun pikeun ngahémat waktos jeung tanaga',
    'quick.online_letter': 'Surat Online',
    'quick.online_letter_desc': 'Ngadamel surat katerangan kalayan gampang',
    'quick.village_umkm': 'UMKM Désa',
    'quick.village_umkm_desc': 'Tingali produk lokal désa',
    'quick.citizen_report': 'Laporan Warga',
    'quick.citizen_report_desc': 'Sampaikan keluhan jeung aspirasi',
    'quick.social_aid': 'Info Bansos',
    'quick.social_aid_desc': 'Informasi bantuan sosial panganyarna',
    'quick.job_market': 'Pasar Pagawéan',
    'quick.job_market_desc': 'Néangan jasa jeung pagawé lokal',
    'quick.population': 'Daptar Penduduk',
    'quick.population_desc': 'Update data kependudukan',
    'quick.transparency': 'Transparansi',
    'quick.transparency_desc': 'Laporan keuangan désa',
    'quick.payment': 'Pembayaran',
    'quick.payment_desc': 'Mayar retribusi jeung pajeg',
    
    // Stats Section
    'stats.title': 'Data Désa Cilame',
    'stats.subtitle': 'Informasi statistik panganyarna ngeunaan kaayaan démografis jeung ékonomi désa',
    'stats.total_population': 'Total Penduduk',
    'stats.population_subtitle': 'Jiwa kadaptar',
    'stats.family_heads': 'Kapala Kulawarga',
    'stats.family_subtitle': 'KK aktip',
    'stats.active_umkm': 'UMKM Aktip',
    'stats.umkm_subtitle': 'Usaha lokal',
    'stats.growth': 'Pertumbuhan',
    'stats.growth_subtitle': 'Ékonomi taun ieu',
    
    // News Section
    'news.title': 'Béja Panganyarna',
    'news.subtitle': 'Turutan kamekaran panganyarna ti Désa Cilame',
    'news.view_all': 'Tingali Sadaya Béja',
    'news.read_more': 'Baca Salengkapna',
    
    // Services
    'services.title': 'Palayanan Digital Désa Cilame',
    'services.subtitle': 'Ngarasakeun rupa-rupa palayanan digital anu ngagampangkeun kahirupan masarakat désa',
    'services.information_portal': 'Portal Informasi',
    'services.information_desc': 'Béja, pengumuman, jeung jadwal palayanan',
    'services.job_market': 'Pasar Tenaga Pagawéan',
    'services.job_market_desc': 'Néangan jasa jeung pagawé lokal',
    'services.umkm_directory': 'Direktori UMKM',
    'services.umkm_desc': 'Toko online pikeun produk lokal',
    'services.financial_transparency': 'Transparansi Keuangan',
    'services.financial_desc': 'Laporan APBDes jeung realisasi',
    
    // Contact Section
    'contact.title': 'Kontak Désa Cilame',
    'contact.subtitle': 'Kami siap ngalayanan anjeun kalayan sapenuh ati. Ulah ragu pikeun ngahubungi kami pikeun rupa-rupa kaperluan administrasi jeung palayanan désa.',
    'contact.service_hours_title': 'JAM PALAYANAN DESA CILAME',
    'contact.service_days_title': 'Poé & Waktos Palayanan',
    'contact.monday_thursday': 'Senén – Kemis',
    'contact.friday': 'Jumaah',
    'contact.weekend_holiday': 'Saptu – Minggu & Poé Libur Nasional',
    'contact.closed': 'Tutup',
    'contact.break_hours_title': 'Jam Istirahat',
    'contact.notes_title': 'Catetan',
    'contact.note_1': 'Datang leuwih awal pikeun ngahindarkeun antrian.',
    'contact.note_2': 'Pastikan sadaya dokumén sarat geus lengkep sateuacan ngajukeun palayanan.',
    'contact.quick_message': 'Pesen Gancang',
    'contact.full_name': 'Nami Lengkep',
    'contact.email': 'Email',
    'contact.message': 'Pesen Anjeun',
    'contact.send_message': 'Kirim Pesen',
    'contact.office_hours': 'Senén - Kemis: 08.00 - 16.00 | Jumaah: 08.00 - 11.30 | Saptu - Minggu jeung Libur Nasional: Tutup',
    
    // Footer
    'footer.description': 'Portal digital resmi Désa Cilame pikeun ngalayanan masarakat kalayan téknologi modéren.',
    'footer.services': 'Palayanan',
    'footer.help': 'Bantuan',
    'footer.guide': 'Panduan',
    'footer.faq': 'FAQ',
    'footer.follow_us': 'Turutan Kami',
    'footer.copyright': '© 2025 Désa Cilame. Sadaya hak cipta dilindungi.',
    
    // Chatbot
    'chatbot.title': 'Asistén Désa Cilame',
    'chatbot.status': 'Online • Siap ngabantosan anjeun',
    'chatbot.greeting': 'Halo! Abdi Asistén Virtual Désa Cilame. Aya anu tiasa abdi bantosan?',
    'chatbot.quick_questions': 'Patarosan umum:',
    'chatbot.letter_guide': 'Cara ngadamel surat katerangan',
    'chatbot.social_aid_info': 'Info bantuan sosial',
    'chatbot.service_schedule': 'Jadwal palayanan',
    'chatbot.village_contact': 'Kontak désa',
    'chatbot.whatsapp': 'Chat via WhatsApp',
    'chatbot.type_message': 'Ketik pesen...',
    'chatbot.response': 'Hatur nuhun kana patarosan anjeun. Tim kami bakal geura-giru ngabantosan anjeun.',
    
    // Announcements
    'announcement.social_aid': '🔔 Pendaptaran Bantuan Sosial PKH Tahap II dibuka dugi ka 31 Januari 2025',
    'announcement.online_service': '📋 Palayanan Surat Katerangan Online ayeuna sayaga 24/7',
    'announcement.market': '🏪 Pasar Rakyat Désa Cilame buka unggal Salasa jeung Jumaah',
    'announcement.budget_report': '💰 Laporan APBDes Triwulan IV parantos dipublikasi',
    'announcement.latest': 'Panganyarna',
    
    // Information Page
    'info.title': 'Portal Informasi Désa',
    'info.subtitle': 'Aksés informasi panganyarna, pengumuman resmi, jadwal palayanan, jeung dokumén publik Désa Cilame',
    'info.search_placeholder': 'Néangan béja, pengumuman, atanapi dokumén...',
    'info.all_categories': 'Sadayana',
    'info.announcements': 'Pengumuman',
    'info.news': 'Béja',
    'info.service_schedule': 'Jadwal Palayanan',
    'info.public_documents': 'Dokumén Publik',
    'info.latest_info': 'Informasi Panganyarna',
    'info.service_schedule_title': 'Jadwal Palayanan',
    'info.public_documents_title': 'Dokumén Publik',
    'info.emergency_contact': 'Kontak Darurat',
    'info.police': 'Polsek: 110',
    'info.fire_dept': 'Pemadam: 113',
    'info.ambulance': 'Ambulans: 118',
    'info.village_office': 'Désa',
    'info.download': 'Unduh',
    'info.no_results': 'Teu aya informasi anu kapanggih',
    
    // Job Market Page
    'job.title': 'Pasar Tenaga Pagawéan Lokal',
    'job.subtitle': 'Panggihan jasa jeung pagawé dipercaya di Désa Cilame kalayan sistem booking jeung pembayaran anu aman',
    'job.search_placeholder': 'Néangan pagawé, jasa, atanapi kaahlian...',
    'job.all_categories': 'Sadaya Kategori',
    'job.construction': 'Tukang jeung Konstruksi',
    'job.housekeeping': 'Pembantu Rumah Tangga',
    'job.agriculture': 'Pertanian jeung Kebon',
    'job.automotive': 'Otomotif',
    'job.electronics': 'Service Éléktronik',
    'job.culinary': 'Jasa Kuliner',
    'job.others': 'Séjénna',
    'job.all_locations': 'Sadaya Lokasi',
    'job.center': 'Pusat Désa',
    'job.north': 'Cilame Kalér',
    'job.south': 'Cilame Kidul',
    'job.east': 'Cilame Wétan',
    'job.west': 'Cilame Kulon',
    'job.showing_workers': 'Nunjukkeun {count} pagawé sayaga',
    'job.per_hour': 'per jam',
    'job.completed_jobs': 'gawéan réngsé',
    'job.booking': 'Booking',
    'job.available': 'Sayaga',
    'job.busy_until': 'Sibuk dugi ka Minggu',
    'job.no_workers': 'Teu aya pagawé anu cocog jeung panéangan anjeun',
    'job.join_worker': 'Hoyong Gabung Janten Pagawé?',
    'job.join_description': 'Daptarkeun kaahlian anjeun jeung kéngingkeun panghasilan tambahan ti jasa anu anjeun tawarkeun',
    'job.register_worker': 'Daptar Janten Pagawé',
    
    // UMKM Page
    'umkm.title': 'Direktori UMKM Désa Cilame',
    'umkm.subtitle': 'Panggihan jeung dukung produk lokal berkualitas ti usaha mikro, alit, jeung sedeng di Désa Cilame',
    'umkm.search_placeholder': 'Néangan UMKM, produk, atanapi palayanan...',
    'umkm.all_categories': 'Sadaya Kategori',
    'umkm.culinary': 'Kuliner',
    'umkm.fashion': 'Fashion jeung Aksésoris',
    'umkm.handicraft': 'Karajinan Leungeun',
    'umkm.agriculture': 'Produk Pertanian',
    'umkm.services': 'Jasa jeung Palayanan',
    'umkm.electronics': 'Éléktronik',
    'umkm.beauty': 'Kacantikan jeung Kaséhatan',
    'umkm.kuliner': 'Kuliner',
    'umkm.kerajinan': 'Karajinan Leungeun',
    'umkm.pertanian': 'Produk Pertanian',
    'umkm.kosmetik': 'Kacantikan jeung Kosmetik',
    'umkm.Meubelair': 'Meubelair',
    'umkm.employees': 'Pagawé',
    'umkm.featured': 'UMKM Unggulan',
    'umkm.all_umkm': 'Sadaya UMKM',
    'umkm.category': 'Kategori',
    'umkm.showing_all': 'Nunjukkeun sadaya UMKM',
    'umkm.popular_products': 'Produk Populér:',
    'umkm.view_store': 'Tingali Toko',
    'umkm.contact': 'Kontak',
    'umkm.products_available': 'produk sayaga',
    'umkm.no_results': 'Teu aya UMKM anu cocog jeung panéangan anjeun',
    'umkm.register_business': 'Hoyong Ngadaptarkeun Usaha Anjeun?',
    'umkm.register_description': 'Gabung jeung direktori UMKM Désa Cilame jeung jangkauan langkung seueur palanggan',
    'umkm.register_umkm': 'Daptar UMKM',
    
    // UMKM Detail Page
    'common.back': 'Balik',
    'umkm.store_not_found': 'UMKM Teu Kapanggih',
    'umkm.back_to_list': 'Balik ka Daptar UMKM',
    'umkm.contact_store': 'Kontak Toko',
    'umkm.call_now': 'Telepon Ayeuna',
    'umkm.chat_whatsapp': 'Chat WhatsApp',
    'umkm.view_location': 'Tingali Lokasi',
    'umkm.store_stats': 'Statistik Toko',
    'umkm.rating': 'Rating',
    'umkm.total_reviews': 'Total Ulasan',
    'umkm.products': 'Produk',
    'umkm.established_year': 'Taun Diadegkeun',
    'umkm.similar_stores': 'Toko Sarupa',
    'umkm.view_all_umkm': 'Tingali Sadaya UMKM',
    'umkm.specialties': 'Spésialisasi',
    'umkm.featured_products': 'Produk Unggulan',
    'umkm.order': 'Pesen',
    'umkm.since': 'Saprak',
    'umkm.owner': 'Juragan',
    'umkm.reviews': 'ulasan',
    
    // Transparency Page
    'transparency.title': 'Transparansi Keuangan Désa',
    'transparency.subtitle': 'Kabuka informasi keuangan jeung palaksanaan program pangwangunan pikeun kapercayaan masarakat',
    'transparency.year': 'Taun:',
    'transparency.period': 'Période:',
    'transparency.annual': 'Taunan',
    'transparency.quarter_4': 'Triwulan IV',
    'transparency.quarter_3': 'Triwulan III',
    'transparency.quarter_2': 'Triwulan II',
    'transparency.quarter_1': 'Triwulan I',
    'transparency.total_budget': 'Total Anggaran',
    'transparency.income_realization': 'Realisasi Pendapatan',
    'transparency.expense_realization': 'Realisasi Belanja',
    'transparency.remaining_budget': 'Sisa Anggaran',
    'transparency.income_breakdown': 'Rincian Pendapatan',
    'transparency.expense_breakdown': 'Rincian Belanja',
    'transparency.program_progress': 'Progress Program Pangwangunan',
    'transparency.financial_reports': 'Laporan Keuangan',
    'transparency.completed': 'Réngsé',
    'transparency.ongoing': 'Lumangsung',
    'transparency.program_completed': 'Program parantos réngsé dilaksanakeun',
    'transparency.program_ongoing': 'Program nuju dina tahap palaksanaan',
    'transparency.need_more_info': 'Peryogi Informasi Langkung Lengkep?',
    'transparency.contact_finance': 'Kontak Bagian Keuangan Désa pikeun panjelasan detil ngeunaan laporan keuangan',
    'transparency.ask_question': 'Ajukan Patarosan',
    'transparency.schedule_consultation': 'Jadwalkeun Konsultasi',
    'transparency.downloads': 'unduhan',
    
    // Additional UI Elements
    'ui.view_details': 'Tingali Detil',
    'ui.send': 'Kirim',
    'ui.save': 'Simpen',
    'ui.cancel': 'Bolay',
    'ui.close': 'Tutup',
    'ui.edit': 'Édit',
    'ui.delete': 'Hapus',
    'ui.confirm': 'Konfirmasi',
    'ui.loading': 'Nuju dimuat...',
    'ui.search': 'Téang',
    'ui.filter': 'Saringan',
    'ui.sort': 'Susun',
    'ui.next': 'Salajengna',
    'ui.previous': 'Saméméhna',
    'ui.back': 'Balik',
    'ui.home': 'Tepas',
    'ui.menu': 'Menu',
    'ui.settings': 'Setélan',
    'ui.profile': 'Profil',
    'ui.logout': 'Kaluar',
    'ui.login': 'Lebet',
    'ui.register': 'Daptar',
    'ui.submit': 'Kirim',
    'ui.reset': 'Reset',
    'ui.clear': 'Beresihan',
    'ui.select': 'Pilih',
    'ui.choose': 'Pilih',
    'ui.upload': 'Unggah',
    'ui.download': 'Unduh',
    'ui.print': 'Cetak',
    'ui.share': 'Bagikeun',
    'ui.copy': 'Salin',
    'ui.paste': 'Témpél',
    'ui.cut': 'Potong',
    'ui.undo': 'Balikkeun',
    'ui.redo': 'Ulang',
    'ui.refresh': 'Refresh',
    'ui.reload': 'Muat Ulang',
    'ui.update': 'Update',
    'ui.new': 'Anyar',
    'ui.add': 'Tambah',
    'ui.remove': 'Cabut',
    'ui.show': 'Témbongkeun',
    'ui.hide': 'Sumputkeun',
    'ui.expand': 'Legakeun',
    'ui.collapse': 'Lipetkeun',
    'ui.maximize': 'Gedékeun',
    'ui.minimize': 'Leutikkeun',
    'ui.fullscreen': 'Layar Pinuh',
    'ui.exit_fullscreen': 'Kaluar Layar Pinuh',
    'ui.play': 'Putar',
    'ui.pause': 'Reureuh',
    'ui.stop': 'Eureun',
    'ui.record': 'Rékam',
    'ui.mute': 'Bisu',
    'ui.unmute': 'Hurungkeun Sora',
    'ui.volume': 'Volume',
    'ui.brightness': 'Caang',
    'ui.contrast': 'Kontras',
    'ui.zoom_in': 'Gedékeun',
    'ui.zoom_out': 'Leutikkeun',
    'ui.fit_to_screen': 'Cocogkeun ka Layar',
    'ui.rotate': 'Puterkeun',
    'ui.flip': 'Balikkeun',
    'ui.crop': 'Potong',
    'ui.resize': 'Robah Ukuran',
    'ui.move': 'Pindahkeun',
    'ui.duplicate': 'Gandakeun',
    'ui.rename': 'Ganti Ngaran',
    'ui.properties': 'Sipat',
    'ui.info': 'Info',
    'ui.help': 'Bantuan',
    'ui.about': 'Ngeunaan',
    'ui.version': 'Vérsi',
    'ui.license': 'Lisénsi',
    'ui.terms': 'Sarat',
    'ui.privacy': 'Privasi',
    'ui.cookies': 'Cookies',
    'ui.feedback': 'Tanggapan',
    'ui.report': 'Laporan',
    'ui.bug': 'Bug',
    'ui.feature_request': 'Pamundut Fitur',
    'ui.contact_support': 'Kontak Dukungan',
    'ui.faq': 'FAQ',
    'ui.tutorial': 'Tutorial',
    'ui.guide': 'Panduan',
    'ui.documentation': 'Dokumentasi',
    'ui.changelog': 'Log Parobahan',
    'ui.release_notes': 'Catetan Rilis',
    'ui.whats_new': 'Naon Anyar',
    'ui.coming_soon': 'Badé Datang',
    'ui.under_construction': 'Nuju Diwangun',
    'ui.maintenance': 'Pangropéa',
    'ui.offline': 'Offline',
    'ui.online': 'Online',
    'ui.connected': 'Nyambung',
    'ui.disconnected': 'Pegatna Sambungan',
    'ui.syncing': 'Nuju Sinkronisasi',
    'ui.synced': 'Geus Sinkron',
    'ui.error': 'Kasalahan',
    'ui.warning': 'Peringatan',
    'ui.success': 'Suksés',
    'ui.info_message': 'Informasi',
    'ui.notification': 'Béwara',
    'ui.alert': 'Waspada',
    'ui.reminder': 'Pangéling',
    'ui.message': 'Pesen',
    'ui.email': 'Email',
    'ui.phone': 'Telepon',
    'ui.address': 'Alamat',
    'ui.contact': 'Hubungi',
    'ui.name': 'Ngaran',
    'ui.username': 'Ngaran Pamaké',
    'ui.password': 'Kecap Sandi',
    'ui.confirm_password': 'Konfirmasi Kecap Sandi',
    'ui.old_password': 'Kecap Sandi Heubeul',
    'ui.new_password': 'Kecap Sandi Anyar',
    'ui.forgot_password': 'Hilap Kecap Sandi',
    'ui.reset_password': 'Reset Kecap Sandi',
    'ui.change_password': 'Ganti Kecap Sandi',
    'ui.remember_me': 'Inget Abdi',
    'ui.stay_logged_in': 'Tetep Lebet',
    'ui.sign_in': 'Lebet',
    'ui.sign_out': 'Kaluar',
    'ui.sign_up': 'Daptar',
    'ui.create_account': 'Jieun Akun',
    'ui.account': 'Akun',
    'ui.dashboard': 'Dashboard',
    'ui.overview': 'Tinjauan',
    'ui.summary': 'Ringkesan',
    'ui.details': 'Detil',
    'ui.description': 'Pedaran',
    'ui.title': 'Judul',
    'ui.subtitle': 'Subjudul',
    'ui.heading': 'Judul',
    'ui.content': 'Eusi',
    'ui.body': 'Awak',
    'ui.footer': 'Footer',
    'ui.header': 'Header',
    'ui.sidebar': 'Sidebar',
    'ui.navigation': 'Navigasi',
    'ui.breadcrumb': 'Breadcrumb',
    'ui.pagination': 'Paginasi',
    'ui.page': 'Kaca',
    'ui.pages': 'Kaca-kaca',
    'ui.first': 'Kahiji',
    'ui.last': 'Panungtung',
    'ui.of': 'ti',
    'ui.total': 'Total',
    'ui.count': 'Jumlah',
    'ui.number': 'Nomer',
    'ui.amount': 'Jumlah',
    'ui.quantity': 'Kuantitas',
    'ui.price': 'Harga',
    'ui.cost': 'Biaya',
    'ui.fee': 'Biaya',
    'ui.tax': 'Pajeg',
    'ui.discount': 'Diskon',
    'ui.total_amount': 'Total Jumlah',
    'ui.subtotal': 'Subtotal',
    'ui.grand_total': 'Total Ageung',
    'ui.balance': 'Saldo',
    'ui.credit': 'Krédit',
    'ui.debit': 'Débit',
    'ui.income': 'Panghasilan',
    'ui.expense': 'Pengeluaran',
    'ui.profit': 'Kauntungan',
    'ui.loss': 'Karugian',
    'ui.revenue': 'Panghasilan',
    'ui.budget': 'Anggaran',
    'ui.forecast': 'Ramalan',
    'ui.actual': 'Aktual',
    'ui.target': 'Target',
    'ui.goal': 'Tujuan',
    'ui.objective': 'Objektif',
    'ui.milestone': 'Milestone',
    'ui.deadline': 'Wates Waktu',
    'ui.due_date': 'Tanggal Jatuh Tempo',
    'ui.start_date': 'Tanggal Mimiti',
    'ui.end_date': 'Tanggal Ahir',
    'ui.created_date': 'Tanggal Dijieun',
    'ui.modified_date': 'Tanggal Dirobah',
    'ui.published_date': 'Tanggal Diterbitkeun',
    'ui.expiry_date': 'Tanggal Kadaluwarsa',
    'ui.birth_date': 'Tanggal Lahir',
    'ui.age': 'Umur',
    'ui.gender': 'Jenis Kelamin',
    'ui.male': 'Lalaki',
    'ui.female': 'Awéwé',
    'ui.other': 'Séjén',
    'ui.status': 'Status',
    'ui.active': 'Aktip',
    'ui.inactive': 'Teu Aktip',
    'ui.enabled': 'Diaktipkeun',
    'ui.disabled': 'Ditumpurkeun',
    'ui.public': 'Umum',
    'ui.private': 'Pribadi',
    'ui.draft': 'Draf',
    'ui.published': 'Diterbitkeun',
    'ui.pending': 'Nungguan',
    'ui.approved': 'Disatujuan',
    'ui.rejected': 'Ditolak',
    'ui.completed': 'Réngsé',
    'ui.in_progress': 'Nuju Dijalankeun',
    'ui.cancelled': 'Dibatalkeun',
    'ui.expired': 'Kadaluwarsa',
    'ui.valid': 'Valid',
    'ui.invalid': 'Teu Valid',
    'ui.required': 'Diperlukeun',
    'ui.optional': 'Pilihan',
    'ui.recommended': 'Disarankeun',
    'ui.featured': 'Diunggulan',
    'ui.popular': 'Populér',
    'ui.trending': 'Trending',
    'ui.new_item': 'Anyar',
    'ui.updated': 'Diperbarui',
    'ui.latest': 'Panganyarna',
    'ui.recent': 'Anyar',
    'ui.older': 'Langkung Heubeul',
    'ui.newest': 'Panganyarna',
    'ui.oldest': 'Pangheulana',
    'ui.top': 'Luhur',
    'ui.bottom': 'Handap',
    'ui.left': 'Kénca',
    'ui.right': 'Katuhu',
    'ui.center': 'Tengah',
    'ui.middle': 'Tengah',
    'ui.beginning': 'Awal',
    'ui.end': 'Ahir',
    'ui.start': 'Mimiti',
    'ui.finish': 'Réngsé',
    'ui.continue': 'Teruskeun',
    'ui.skip': 'Loncatan',
    'ui.retry': 'Coba Deui',
    'ui.try_again': 'Coba Deui',
    'ui.yes': 'Enya',
    'ui.no': 'Henteu',
    'ui.ok': 'OK',
    'ui.done': 'Réngsé',
    'ui.finished': 'Réngsé',
    'ui.complete': 'Lengkep',
    'ui.incomplete': 'Teu Lengkep',
    'ui.partial': 'Sabagian',
    'ui.full': 'Pinuh',
    'ui.empty': 'Kosong',
    'ui.none': 'Euweuh',
    'ui.all': 'Sadayana',
    'ui.some': 'Sabagian',
    'ui.many': 'Loba',
    'ui.few': 'Saeutik',
    'ui.more': 'Langkung',
    'ui.less': 'Kurang',
    'ui.most': 'Paling',
    'ui.least': 'Pangsaeutikna',
    'ui.maximum': 'Maksimum',
    'ui.minimum': 'Minimum',
    'ui.average': 'Rata-rata',
    'ui.median': 'Median',
    'ui.mode': 'Mode',
    'ui.range': 'Rentang',
    'ui.variance': 'Varian',
    'ui.standard_deviation': 'Simpangan Baku',
    'ui.percentage': 'Perséntase',
    'ui.ratio': 'Rasio',
    'ui.proportion': 'Proporsi',
    'ui.rate': 'Laju',
    'ui.frequency': 'Frékuénsi',
    'ui.duration': 'Durasi',
    'ui.time': 'Waktu',
    'ui.date': 'Tanggal',
    'ui.day': 'Poé',
    'ui.week': 'Minggu',
    'ui.month': 'Bulan',
    'ui.year': 'Taun',
    'ui.hour': 'Jam',
    'ui.minute': 'Menit',
    'ui.second': 'Detik',
    'ui.today': 'Dinten Ieu',
    'ui.yesterday': 'Kamari',
    'ui.tomorrow': 'Isukan',
    'ui.now': 'Ayeuna',
    'ui.later': 'Engké',
    'ui.soon': 'Geura-giru',
    'ui.never': 'Pernah',
    'ui.always': 'Salawasna',
    'ui.sometimes': 'Kadang-kadang',
    'ui.often': 'Sering',
    'ui.rarely': 'Jarang',
    'ui.usually': 'Biasana',
    'ui.normally': 'Biasana',
    'ui.typically': 'Biasana',
    'ui.generally': 'Umumna',
    'ui.specifically': 'Husus',
    'ui.exactly': 'Persis',
    'ui.approximately': 'Kira-kira',
    'ui.around': 'Sakitar',
    'ui.nearly': 'Ampir',
    'ui.almost': 'Ampir',
    'ui.quite': 'Rada',
    'ui.very': 'Pisan',
    'ui.extremely': 'Ekstrim',
    'ui.highly': 'Pisan',
    'ui.completely': 'Lengkep',
    'ui.totally': 'Total',
    'ui.entirely': 'Sagemblengna',
    'ui.partially': 'Sabagian',
    'ui.mostly': 'Lolobana',
    'ui.mainly': 'Utamana',
    'ui.primarily': 'Utamana',
    'ui.basically': 'Dasarna',
    'ui.essentially': 'Intina',
    'ui.fundamentally': 'Dasarna',
    'ui.originally': 'Asalna',
    'ui.initially': 'Mimitina',
    'ui.finally': 'Ahirna',
    'ui.eventually': 'Ahirna',
    'ui.ultimately': 'Pamungkasna',
    'ui.consequently': 'Akibatna',
    'ui.therefore': 'Ku kituna',
    'ui.however': 'Sanajan kitu',
    'ui.nevertheless': 'Sanajan kitu',
    'ui.nonetheless': 'Sanajan kitu',
    'ui.otherwise': 'Upami henteu',
    'ui.meanwhile': 'Samentawis',
    'ui.furthermore': 'Salajengna',
    'ui.moreover': 'Salian ti éta',
    'ui.additionally': 'Salian ti éta',
    'ui.also': 'Ogé',
    'ui.too': 'Ogé',
    'ui.as_well': 'Ogé',
    'ui.either': 'Boh',
    'ui.neither': 'Henteu boh',
    'ui.both': 'Duanana',
    'ui.and': 'Jeung',
    'ui.or': 'Atanapi',
    'ui.but': 'Tapi',
    'ui.so': 'Jadi',
    'ui.because': 'Sabab',
    'ui.since': 'Saprak',
    'ui.while': 'Bari',
    'ui.although': 'Sanajan',
    'ui.though': 'Sanajan',
    'ui.unless': 'Iwal',
    'ui.until': 'Dugi',
    'ui.before': 'Saméméh',
    'ui.after': 'Saatos',
    'ui.during': 'Salila',
    'ui.within': 'Dina',
    'ui.without': 'Tanpa',
    'ui.with': 'Kalayan',
    'ui.by': 'Ku',
    'ui.for': 'Pikeun',
    'ui.to': 'Ka',
    'ui.from': 'Ti',
    'ui.in': 'Di',
    'ui.on': 'Dina',
    'ui.at': 'Di',
    'ui.over': 'Leuwih',
    'ui.under': 'Handapeun',
    'ui.above': 'Luhureun',
    'ui.below': 'Handapeun',
    'ui.between': 'Antara',
    'ui.among': 'Diantara',
    'ui.through': 'Ngaliwatan',
    'ui.across': 'Meuntas',
    'ui.along': 'Sapanjang',
    'ui.around_preposition': 'Sabudeureun',
    'ui.near': 'Deukeut',
    'ui.far': 'Jauh',
    'ui.distant': 'Jauh',
    'ui.here': 'Di dieu',
    'ui.there': 'Di dinya',
    'ui.where': 'Dimana',
    'ui.everywhere': 'Dimana-mana',
    'ui.nowhere': 'Teu aya dimana',
    'ui.somewhere': 'Di mana waé',
    'ui.anywhere': 'Di mana waé',
    'ui.inside': 'Di jero',
    'ui.outside': 'Di luar',
    'ui.upstairs': 'Di luhur',
    'ui.downstairs': 'Di handap',
    'ui.indoors': 'Di jero',
    'ui.outdoors': 'Di luar',
    'ui.forward': 'Maju',
    'ui.backward': 'Mundur',
    'ui.ahead': 'Payun',
    'ui.behind': 'Tukangeun',
    'ui.beside': 'Di gigireun',
    'ui.next_to': 'Di gigireun',
    'ui.opposite': 'Sabalikna',
    'ui.facing': 'Nyanghareup',
    'ui.towards': 'Nuju',
    'ui.away': 'Jauh',
    'ui.up': 'Luhur',
    'ui.down': 'Handap',
    'ui.straight': 'Lempeng',
    'ui.diagonal': 'Diagonal',
    'ui.horizontal': 'Horizontal',
    'ui.vertical': 'Vertikal',
    'ui.parallel': 'Paralel',
    'ui.perpendicular': 'Jejeg',
    'ui.circular': 'Buleud',
    'ui.square': 'Pasagi',
    'ui.rectangular': 'Segi opat',
    'ui.triangular': 'Segitiga',
    'ui.round': 'Buleud',
    'ui.flat': 'Datar',
    'ui.curved': 'Melengkung',
    'ui.straight_line': 'Garis lempeng',
    'ui.thick': 'Kandel',
    'ui.thin': 'Ipis',
    'ui.wide': 'Lega',
    'ui.narrow': 'Heureut',
    'ui.broad': 'Lega',
    'ui.slim': 'Ramping',
    'ui.fat': 'Gendut',
    'ui.skinny': 'Kurus',
    'ui.tall': 'Jangkung',
    'ui.short': 'Pondok',
    'ui.long': 'Panjang',
    'ui.brief': 'Singget',
    'ui.deep': 'Jero',
    'ui.shallow': 'Deet',
    'ui.high': 'Luhur',
    'ui.low': 'Handap',
    'ui.big': 'Gedé',
    'ui.small': 'Leutik',
    'ui.large': 'Ageung',
    'ui.tiny': 'Leutik pisan',
    'ui.huge': 'Gedé pisan',
    'ui.enormous': 'Ageung pisan',
    'ui.massive': 'Masif',
    'ui.giant': 'Raksasa',
    'ui.mini': 'Mini',
    'ui.micro': 'Mikro',
    'ui.macro': 'Makro',
    'ui.mega': 'Mega',
    'ui.super': 'Super',
    'ui.ultra': 'Ultra',
    'ui.extra': 'Tambahan',
    'ui.plus': 'Tambah',
    'ui.minus': 'Kurang',
    'ui.equal': 'Sarua',
    'ui.not_equal': 'Henteu sarua',
    'ui.greater': 'Leuwih gedé',
    'ui.lesser': 'Leuwih leutik',
    'ui.better': 'Leuwih hadé',
    'ui.worse': 'Leuwih goréng',
    'ui.best': 'Panghadéna',
    'ui.worst': 'Panggorenga',
    'ui.good': 'Hadé',
    'ui.bad': 'Goréng',
    'ui.excellent': 'Alus pisan',
    'ui.poor': 'Goréng',
    'ui.fair': 'Lumayan',
    'ui.average_quality': 'Rata-rata',
    'ui.superior': 'Unggul',
    'ui.inferior': 'Handap',
    'ui.premium': 'Premium',
    'ui.standard': 'Standar',
    'ui.basic': 'Dasar',
    'ui.advanced': 'Maju',
    'ui.professional': 'Profésional',
    'ui.amateur': 'Amatir',
    'ui.expert': 'Ahli',
    'ui.beginner': 'Pemula',
    'ui.intermediate': 'Menengah',
    'ui.easy': 'Gampang',
    'ui.difficult': 'Hésé',
    'ui.hard': 'Hésé',
    'ui.simple': 'Basajan',
    'ui.complex': 'Rumit',
    'ui.complicated': 'Rumit',
    'ui.straightforward': 'Langsung',
    'ui.unclear': 'Teu jelas',
    'ui.obvious': 'Jelas',
    'ui.hidden': 'Disumputkeun',
    'ui.visible': 'Katingali',
    'ui.invisible': 'Teu katingali',
    'ui.transparent': 'Transparan',
    'ui.opaque': 'Teu transparan',
    'ui.bright': 'Caang',
    'ui.dark': 'Poék',
    'ui.light': 'Caang',
    'ui.heavy': 'Beurat',
    'ui.lightweight': 'Enteng',
    'ui.solid': 'Padet',
    'ui.liquid': 'Cair',
    'ui.gas': 'Gas',
    'ui.hot': 'Panas',
    'ui.cold': 'Tiis',
    'ui.warm': 'Haneut',
    'ui.cool': 'Tiis',
    'ui.freezing': 'Beku',
    'ui.boiling': 'Ngagolak',
    'ui.wet': 'Baseuh',
    'ui.dry': 'Garing',
    'ui.moist': 'Beueus',
    'ui.damp': 'Lembab',
    'ui.humid': 'Lembab',
    'ui.arid': 'Gersang',
    'ui.smooth': 'Lemes',
    'ui.rough': 'Kasar',
    'ui.soft': 'Lemes',
    'ui.hard_texture': 'Keras',
    'ui.sharp': 'Seukeut',
    'ui.blunt': 'Tumpul',
    'ui.pointed': 'Runcing',
    'ui.rounded': 'Buleud',
    'ui.angular': 'Siku',
    'ui.smooth_surface': 'Permukaan lemes',
    'ui.textured': 'Bertekstur',
    'ui.glossy': 'Mengkilap',
    'ui.matte': 'Matte',
    'ui.shiny': 'Mengkilap',
    'ui.dull': 'Kusam',
    'ui.colorful': 'Warna-warni',
    'ui.colorless': 'Teu warna',
    'ui.monochrome': 'Monokrom',
    'ui.multicolor': 'Warna-warni',
    'ui.red': 'Beureum',
    'ui.blue': 'Biru',
    'ui.green': 'Héjo',
    'ui.yellow': 'Konéng',
    'ui.orange': 'Oranyeu',
    'ui.purple': 'Ungu',
    'ui.pink': 'Merah jambu',
    'ui.brown': 'Coklat',
    'ui.black': 'Hideung',
    'ui.white': 'Bodas',
    'ui.gray': 'Abu-abu',
    'ui.silver': 'Pérak',
    'ui.gold': 'Emas',
    'ui.bronze': 'Perunggu',
    'ui.copper': 'Tambaga',
    'ui.metallic': 'Logam',
    'ui.wooden': 'Kai',
    'ui.plastic': 'Plastik',
    'ui.glass': 'Kaca',
    'ui.ceramic': 'Keramik',
    'ui.fabric': 'Kain',
    'ui.leather': 'Kulit',
    'ui.rubber': 'Karét',
    'ui.paper': 'Kertas',
    'ui.cardboard': 'Karton',
    'ui.stone': 'Batu',
    'ui.concrete': 'Beton',
    'ui.brick': 'Bata',
    'ui.tile': 'Ubin',
    'ui.marble': 'Marmer',
    'ui.granite': 'Granit',
    'ui.sand': 'Keusik',
    'ui.soil': 'Taneuh',
    'ui.mud': 'Leutak',
    'ui.clay': 'Liat',
    'ui.ice': 'És',
    'ui.snow': 'Salju',
    'ui.water': 'Cai',
    'ui.oil': 'Minyak',
    'ui.fire': 'Seuneu',
    'ui.smoke': 'Haseup',
    'ui.steam': 'Uap',
    'ui.air': 'Hawa',
    'ui.wind': 'Angin',
    'ui.breeze': 'Angin sepoi',
    'ui.storm': 'Badai',
    'ui.rain': 'Hujan',
    'ui.sun': 'Panonpoé',
    'ui.moon': 'Bulan',
    'ui.star': 'Béntang',
    'ui.cloud': 'Méga',
    'ui.sky': 'Langit',
    'ui.earth': 'Bumi',
    'ui.ground': 'Taneuh',
    'ui.floor': 'Lantai',
    'ui.ceiling': 'Plafon',
    'ui.wall': 'Témbok',
    'ui.door': 'Panto',
    'ui.window': 'Jandela',
    'ui.roof': 'Hateup',
    'ui.building': 'Gedong',
    'ui.house': 'Imah',
    'ui.room': 'Kamar',
    'ui.kitchen': 'Dapur',
    'ui.bathroom': 'Kamar mandi',
    'ui.bedroom': 'Kamar tidur',
    'ui.living_room': 'Ruang tamu',
    'ui.office': 'Kantor',
    'ui.school': 'Sakola',
    'ui.hospital': 'Rumah sakit',
    'ui.store': 'Toko',
    'ui.market': 'Pasar',
    'ui.restaurant': 'Réstoran',
    'ui.hotel': 'Hotél',
    'ui.bank': 'Bank',
    'ui.library': 'Perpustakaan',
    'ui.museum': 'Museum',
    'ui.park': 'Taman',
    'ui.garden': 'Kebon',
    'ui.farm': 'Tegalan',
    'ui.forest': 'Leuweung',
    'ui.mountain': 'Gunung',
    'ui.hill': 'Pasir',
    'ui.valley': 'Lebak',
    'ui.river': 'Walungan',
    'ui.lake': 'Danau',
    'ui.sea': 'Laut',
    'ui.ocean': 'Samudra',
    'ui.beach': 'Pantai',
    'ui.island': 'Pulo',
    'ui.bridge': 'Sasak',
    'ui.road': 'Jalan',
    'ui.street': 'Jalan',
    'ui.path': 'Jalur',
    'ui.sidewalk': 'Trotoar',
    'ui.intersection': 'Simpang',
    'ui.corner': 'Pojok',
    'ui.traffic_light': 'Lampu lalu lintas',
    'ui.sign': 'Tanda',
    'ui.billboard': 'Papan reklame',
    'ui.poster': 'Poster',
    'ui.banner': 'Spanduk',
    'ui.flag': 'Bandéra',
    'ui.symbol': 'Simbol',
    'ui.icon': 'Ikon',
    'ui.logo': 'Logo',
    'ui.brand': 'Mérek',
    'ui.trademark': 'Mérek dagang',
    'ui.copyright': 'Hak cipta',
    'ui.patent': 'Patén',
    'ui.license_document': 'Lisénsi',
    'ui.certificate': 'Sertifikat',
    'ui.diploma': 'Diploma',
    'ui.degree': 'Gelar',
    'ui.award': 'Panghargaan',
    'ui.prize': 'Hadiah',
    'ui.trophy': 'Trofi',
    'ui.medal': 'Medali',
    'ui.ribbon': 'Pita',
    'ui.badge': 'Lencana',
    'ui.sticker': 'Stiker',
    'ui.label': 'Label',
    'ui.tag': 'Tag',
    'ui.bookmark': 'Bookmark',
    'ui.favorite': 'Favorit',
    'ui.like': 'Resep',
    'ui.dislike': 'Teu resep',
    'ui.love': 'Cinta',
    'ui.hate': 'Benci',
    'ui.follow': 'Turutan',
    'ui.unfollow': 'Teu turutan',
    'ui.subscribe': 'Langganan',
    'ui.unsubscribe': 'Batal langganan',
    'ui.join': 'Gabung',
    'ui.leave': 'Ninggalkeun',
    'ui.enter': 'Asup',
    'ui.exit': 'Kaluar',
    'ui.open': 'Buka',
    'ui.close_verb': 'Tutup',
    'ui.lock': 'Konci',
    'ui.unlock': 'Buka konci',
    'ui.secure': 'Aman',
    'ui.insecure': 'Teu aman',
    'ui.safe': 'Aman',
    'ui.dangerous': 'Bahaya',
    'ui.risk': 'Résiko',
    'ui.threat': 'Ancaman',
    'ui.protection': 'Panyalindungan',
    'ui.security': 'Kaamanan',
    'ui.privacy_noun': 'Privasi',
    'ui.confidential': 'Rahasia',
    'ui.secret': 'Rahasia',
    'ui.hidden_adjective': 'Disumputkeun',
    'ui.revealed': 'Diungkabkeun',
    'ui.exposed': 'Kakeunaan',
    'ui.covered': 'Ditutupan',
    'ui.protected': 'Dilindungi',
    'ui.unprotected': 'Teu dilindungi',
    'ui.encrypted': 'Diénkripsi',
    'ui.decrypted': 'Didékripsi',
    'ui.encoded': 'Diénkode',
    'ui.decoded': 'Didékode',
    'ui.compressed': 'Dikompres',
    'ui.uncompressed': 'Teu dikompres',
    'ui.archived': 'Diarsipkeun',
    'ui.extracted': 'Diekstrak',
    'ui.imported': 'Diimpor',
    'ui.exported': 'Diekspor',
    'ui.uploaded': 'Diunggah',
    'ui.downloaded': 'Diunduh',
    'ui.installed': 'Dipasang',
    'ui.uninstalled': 'Dicopot',
    'ui.activated': 'Diaktipkeun',
    'ui.deactivated': 'Ditumpurkeun',
    'ui.enabled_past': 'Diaktipkeun',
    'ui.disabled_past': 'Ditumpurkeun',
    'ui.turned_on': 'Dihurungkeun',
    'ui.turned_off': 'Dipareuman',
    'ui.started': 'Dimimitian',
    'ui.stopped': 'Dieureunkeun',
    'ui.paused': 'Direureuhkeun',
    'ui.resumed': 'Diteruskeun',
    'ui.restarted': 'Dimulai deui',
    'ui.rebooted': 'Di-reboot',
    'ui.shutdown': 'Dipareuman',
    'ui.powered_on': 'Dihurungkeun',
    'ui.powered_off': 'Dipareuman',
    'ui.connected_past': 'Disambungkeun',
    'ui.disconnected_past': 'Dipegatkeun',
    'ui.linked': 'Dihubungkeun',
    'ui.unlinked': 'Dipegatkeun',
    'ui.attached': 'Dipasang',
    'ui.detached': 'Dicopot',
    'ui.mounted': 'Di-mount',
    'ui.unmounted': 'Di-unmount',
    'ui.plugged': 'Dipasang',
    'ui.unplugged': 'Dicopot',
    'ui.charged': 'Dicas',
    'ui.discharged': 'Habis',
    'ui.full_battery': 'Batré pinuh',
    'ui.low_battery': 'Batré lemah',
    'ui.empty_battery': 'Batré kosong',
    'ui.charging': 'Nuju dicas',
    'ui.not_charging': 'Teu dicas',
    'ui.power': 'Listrik',
    'ui.energy': 'Énergi',
    'ui.fuel': 'Bahan bakar',
    'ui.gas_fuel': 'Bensin',
    'ui.electricity': 'Listrik',
    'ui.solar': 'Surya',
    'ui.wind_energy': 'Angin',
    'ui.water_power': 'Cai',
    'ui.nuclear': 'Nuklir',
    'ui.renewable': 'Terbarukan',
    'ui.sustainable': 'Berkelanjutan',
    'ui.eco_friendly': 'Ramah lingkungan',
    'ui.green_technology': 'Téknologi héjo',
    'ui.clean': 'Beresih',
    'ui.dirty': 'Kotor',
    'ui.polluted': 'Tercemar',
    'ui.contaminated': 'Terkontaminasi',
    'ui.pure': 'Murni',
    'ui.mixed': 'Campuran',
    'ui.separated': 'Dipisahkeun',
    'ui.combined': 'Digabungkeun',
    'ui.merged': 'Digabung',
    'ui.split': 'Dibeulah',
    'ui.divided': 'Dibagi',
    'ui.multiplied': 'Dikali',
    'ui.added': 'Ditambah',
    'ui.subtracted': 'Dikurang',
    'ui.calculated': 'Dihitung',
    'ui.computed': 'Dihitung',
    'ui.processed': 'Diproses',
    'ui.analyzed': 'Dianalisis',
    'ui.evaluated': 'Dievaluasi',
    'ui.assessed': 'Dinilai',
    'ui.measured': 'Diukur',
    'ui.weighed': 'Ditimbang',
    'ui.counted': 'Dihitung',
    'ui.sorted': 'Diurutkeun',
    'ui.organized': 'Diatur',
    'ui.arranged': 'Disusun',
    'ui.structured': 'Disusun',
    'ui.formatted': 'Diformat',
    'ui.styled': 'Distilkeun',
    'ui.designed': 'Dirancang',
    'ui.created': 'Dijieun',
    'ui.built': 'Diwangun',
    'ui.constructed': 'Dikonstruksi',
    'ui.assembled': 'Dirakit',
    'ui.manufactured': 'Diproduksi',
    'ui.produced': 'Diproduksi',
    'ui.generated': 'Dihasilkeun',
    'ui.developed': 'Dikembangkeun',
    'ui.improved': 'Ditingkatkeun',
    'ui.enhanced': 'Ditingkatkeun',
    'ui.upgraded': 'Di-upgrade',
    'ui.downgraded': 'Diturunkeun',
    'ui.optimized': 'Dioptimalkeun',
    'ui.customized': 'Dikustomisasi',
    'ui.personalized': 'Dipersonalisasi',
    'ui.configured': 'Dikonfigurasi',
    'ui.set_up': 'Disetél',
    'ui.initialized': 'Diinisialisasi',
    'ui.prepared': 'Disiapkeun',
    'ui.ready': 'Siap',
    'ui.waiting': 'Nungguan',
    'ui.busy': 'Sibuk',
    'ui.idle': 'Nganggur',
    'ui.working': 'Gawé',
    'ui.resting': 'Istirahat',
    'ui.sleeping': 'Saré',
    'ui.awake': 'Hudang',
    'ui.alert_adjective': 'Waspada',
    'ui.focused': 'Fokus',
    'ui.distracted': 'Kaganggu',
    'ui.concentrated': 'Konsentrasi',
    'ui.relaxed': 'Santai',
    'ui.stressed': 'Stres',
    'ui.calm': 'Tenang',
    'ui.excited': 'Bungah',
    'ui.nervous': 'Gugup',
    'ui.confident': 'Percaya diri',
    'ui.uncertain': 'Teu yakin',
    'ui.sure': 'Yakin',
    'ui.unsure': 'Teu yakin',
    'ui.positive': 'Positip',
    'ui.negative': 'Négatip',
    'ui.neutral': 'Nétral',
    'ui.optimistic': 'Optimis',
    'ui.pessimistic': 'Pesimis',
    'ui.hopeful': 'Harepan',
    'ui.hopeless': 'Putus asa',
    'ui.happy': 'Bagja',
    'ui.sad': 'Sedih',
    'ui.angry': 'Ambek',
    'ui.peaceful': 'Damai',
    'ui.violent': 'Kekerasan',
    'ui.gentle': 'Lemah lembut',
    'ui.rough_behavior': 'Kasar',
    'ui.kind': 'Bageur',
    'ui.cruel': 'Kejam',
    'ui.friendly': 'Ramah',
    'ui.hostile': 'Musuhan',
    'ui.polite': 'Sopan',
    'ui.rude': 'Kasar',
    'ui.respectful': 'Hormat',
    'ui.disrespectful': 'Teu hormat',
    'ui.honest': 'Jujur',
    'ui.dishonest': 'Teu jujur',
    'ui.truthful': 'Jujur',
    'ui.false': 'Palsu',
    'ui.real': 'Nyata',
    'ui.fake': 'Palsu',
    'ui.genuine': 'Asli',
    'ui.artificial': 'Buatan',
    'ui.natural': 'Alami',
    'ui.synthetic': 'Sintétik',
    'ui.organic': 'Organik',
    'ui.inorganic': 'Anorganik',
    'ui.biological': 'Biologis',
    'ui.chemical': 'Kimia',
    'ui.physical': 'Fisik',
    'ui.mental': 'Mental',
    'ui.emotional': 'Émosional',
    'ui.spiritual': 'Spiritual',
    'ui.intellectual': 'Intelektual',
    'ui.creative': 'Kreatip',
    'ui.artistic': 'Artistik',
    'ui.musical': 'Musik',
    'ui.visual': 'Visual',
    'ui.audio': 'Audio',
    'ui.video': 'Pidéo',
    'ui.image': 'Gambar',
    'ui.picture': 'Gambar',
    'ui.photo': 'Poto',
    'ui.drawing': 'Gambar',
    'ui.painting': 'Lukisan',
    'ui.sketch': 'Sketsa',
    'ui.illustration': 'Ilustrasi',
    'ui.diagram': 'Diagram',
    'ui.chart': 'Bagan',
    'ui.graph': 'Grafik',
    'ui.map': 'Peta',
    'ui.plan': 'Rencana',
    'ui.blueprint': 'Cetak biru',
    'ui.design_noun': 'Desain',
    'ui.layout': 'Tata letak',
    'ui.template': 'Témplat',
    'ui.pattern': 'Pola',
    'ui.style_noun': 'Gaya',
    'ui.theme': 'Téma',
    'ui.color_scheme': 'Skéma warna',
    'ui.font': 'Font',
    'ui.text': 'Téks',
    'ui.content_noun': 'Eusi',
    'ui.data': 'Data',
    'ui.information': 'Informasi',
    'ui.knowledge': 'Pangaweruh',
    'ui.wisdom': 'Hikmah',
    'ui.experience': 'Pangalaman',
    'ui.skill': 'Kaahlian',
    'ui.talent': 'Bakat',
    'ui.ability': 'Kamampuan',
    'ui.capability': 'Kapabilitas',
    'ui.capacity': 'Kapasitas',
    'ui.potential': 'Poténsial',
    'ui.opportunity': 'Kasempetan',
    'ui.chance': 'Kasempetan',
    'ui.possibility': 'Kamungkinan',
    'ui.probability': 'Probabilitas',
    'ui.certainty': 'Kapastian',
    'ui.uncertainty': 'Kateupastian',
    'ui.doubt': 'Ragu',
    'ui.belief': 'Kapercayaan',
    'ui.faith': 'Iman',
    'ui.trust': 'Percaya',
    'ui.confidence': 'Kapercayaan diri',
    'ui.courage': 'Kawani',
    'ui.bravery': 'Kawani',
    'ui.fear': 'Sieun',
    'ui.anxiety': 'Kahariwang',
    'ui.worry': 'Hariwang',
    'ui.concern': 'Prihatin',
    'ui.care': 'Miara',
    'ui.attention': 'Perhatian',
    'ui.focus_noun': 'Fokus',
    'ui.concentration': 'Konsentrasi',
    'ui.effort': 'Usaha',
    'ui.attempt': 'Usaha',
    'ui.try_noun': 'Usaha',
    'ui.failure': 'Kagagalan',
    'ui.achievement': 'Prestasi',
    'ui.accomplishment': 'Pencapaian',
    'ui.victory': 'Kameunangan',
    'ui.defeat': 'Kekalahan',
    'ui.win': 'Meunang',
    'ui.lose': 'Eleh',
    'ui.gain': 'Kauntungan',
    'ui.loss_noun': 'Karugian',
    'ui.benefit': 'Kauntungan',
    'ui.advantage': 'Kaunggulan',
    'ui.disadvantage': 'Karugian',
    'ui.strength': 'Kakuatan',
    'ui.weakness': 'Kalemahan',
    'ui.power_noun': 'Kakuatan',
    'ui.force': 'Kakuatan',
    'ui.energy_noun': 'Énergi',
    'ui.motivation': 'Motivasi',
    'ui.inspiration': 'Inspirasi',
    'ui.encouragement': 'Dorongan',
    'ui.support': 'Dukungan',
    'ui.help_noun': 'Bantuan',
    'ui.assistance': 'Bantuan',
    'ui.aid': 'Bantuan',
    'ui.service': 'Palayanan',
    'ui.favor': 'Bantuan',
    'ui.kindness': 'Kahadéan',
    'ui.generosity': 'Kadermawanan',
    'ui.charity': 'Amal',
    'ui.donation': 'Sumbangan',
    'ui.gift': 'Hadiah',
    'ui.present': 'Hadiah',
    'ui.reward': 'Ganjaran',
    'ui.punishment': 'Hukuman',
    'ui.penalty': 'Denda',
    'ui.fine': 'Denda',
    'ui.fee_noun': 'Biaya',
    'ui.cost_noun': 'Biaya',
    'ui.payment': 'Pembayaran',
    'ui.salary': 'Gaji',
    'ui.wage': 'Upah',
    'ui.income_noun': 'Panghasilan',
    'ui.earnings': 'Panghasilan',
    'ui.profit_noun': 'Kauntungan',
    'ui.revenue_noun': 'Panghasilan',
    'ui.turnover': 'Omzet',
    'ui.investment': 'Investasi',
    'ui.savings': 'Tabungan',
    'ui.debt': 'Hutang',
    'ui.loan': 'Pinjaman',
    'ui.credit_noun': 'Krédit',
    'ui.interest': 'Bunga',
    'ui.tax_noun': 'Pajeg',
    'ui.insurance': 'Asuransi',
    'ui.warranty': 'Garansi',
    'ui.guarantee': 'Jaminan',
    'ui.contract': 'Kontrak',
    'ui.agreement': 'Kasepakatan',
    'ui.deal': 'Kasepakatan',
    'ui.negotiation': 'Negosiasi',
    'ui.discussion': 'Diskusi',
    'ui.conversation': 'Paguneman',
    'ui.dialogue': 'Dialog',
    'ui.communication': 'Komunikasi',
    'ui.message_noun': 'Pesen',
    'ui.letter': 'Surat',
    'ui.mail': 'Surat',
    'ui.email_noun': 'Email',
    'ui.phone_call': 'Telepon',
    'ui.meeting': 'Rapat',
    'ui.conference': 'Konperénsi',
    'ui.presentation': 'Presentasi',
    'ui.speech': 'Pidato',
    'ui.lecture': 'Kuliah',
    'ui.lesson': 'Pelajaran',
    'ui.class': 'Kelas',
    'ui.course': 'Kursus',
    'ui.training': 'Pelatihan',
    'ui.workshop': 'Workshop',
    'ui.seminar': 'Seminar',
    'ui.event': 'Acara',
    'ui.occasion': 'Kasempetan',
    'ui.celebration': 'Perayaan',
    'ui.party': 'Pesta',
    'ui.festival': 'Festival',
    'ui.ceremony': 'Upacara',
    'ui.ritual': 'Ritual',
    'ui.tradition': 'Tradisi',
    'ui.custom': 'Adat',
    'ui.culture': 'Budaya',
    'ui.heritage': 'Warisan',
    'ui.history': 'Sajarah',
    'ui.past': 'Baheula',
    'ui.present_time': 'Ayeuna',
    'ui.future': 'Hareup',
    'ui.timeline': 'Garis waktu',
    'ui.schedule': 'Jadwal',
    'ui.calendar': 'Kalénder',
    'ui.appointment': 'Janjian',
    'ui.reservation': 'Reservasi',
    'ui.booking': 'Booking',
    'ui.ticket': 'Tiket',
    'ui.pass': 'Pas',
    'ui.permit': 'Idin',
    'ui.license_noun': 'Lisénsi',
    'ui.authorization': 'Otorisasi',
    'ui.permission': 'Idin',
    'ui.approval': 'Persetujuan',
    'ui.acceptance': 'Penerimaan',
    'ui.rejection': 'Panolakan',
    'ui.refusal': 'Panolakan',
    'ui.denial': 'Panolakan',
    'ui.confirmation': 'Konfirmasi',
    'ui.verification': 'Verifikasi',
    'ui.validation': 'Validasi',
    'ui.authentication': 'Otentikasi',
    'ui.identification': 'Identifikasi',
    'ui.recognition': 'Pangakuan',
    'ui.acknowledgment': 'Pangakuan',
    'ui.appreciation': 'Apresiasi',
    'ui.gratitude': 'Syukur',
    'ui.thanks': 'Hatur nuhun',
    'ui.welcome_noun': 'Sambutan',
    'ui.greeting': 'Salam',
    'ui.farewell': 'Pamitan',
    'ui.goodbye': 'Pamit',
    'ui.hello': 'Halo',
    'ui.hi': 'Hai',
    'ui.good_morning': 'Wilujeng énjing',
    'ui.good_afternoon': 'Wilujeng siang',
    'ui.good_evening': 'Wilujeng sonten',
    'ui.good_night': 'Wilujeng wengi',
    'ui.please': 'Punten',
    'ui.thank_you': 'Hatur nuhun',
    'ui.you_are_welcome': 'Sami-sami',
    'ui.excuse_me': 'Punten',
    'ui.sorry': 'Hapunten',
    'ui.apology': 'Hapunten',
    'ui.forgiveness': 'Pangampunan',
    'ui.pardon': 'Hampura',
    'ui.congratulations': 'Wilujeng',
    'ui.good_luck': 'Wilujeng',
    'ui.best_wishes': 'Wilujeng',
    'ui.blessing': 'Berkah',
    'ui.prayer': 'Doa',
    'ui.hope_noun': 'Harepan',
    'ui.wish': 'Harepan',
    'ui.dream': 'Impian',
    'ui.goal_noun': 'Tujuan',
    'ui.purpose': 'Tujuan',
    'ui.intention': 'Niat',
    'ui.plan_noun': 'Rencana',
    'ui.strategy': 'Strategi',
    'ui.method': 'Métode',
    'ui.approach': 'Pendekatan',
    'ui.technique': 'Téhnik',
    'ui.procedure': 'Prosedur',
    'ui.process': 'Prosés',
    'ui.system': 'Sistem',
    'ui.mechanism': 'Mékanisme',
    'ui.operation': 'Operasi',
    'ui.function': 'Fungsi',
    'ui.feature': 'Fitur',
    'ui.characteristic': 'Karakteristik',
    'ui.attribute': 'Atribut',
    'ui.property': 'Sipat',
    'ui.quality': 'Kualitas',
    'ui.quantity_noun': 'Kuantitas',
    'ui.measure': 'Ukuran',
    'ui.measurement': 'Pangukuran',
    'ui.dimension': 'Dimensi',
    'ui.size': 'Ukuran',
    'ui.scale': 'Skala',
    'ui.level': 'Tingkat',
    'ui.degree_noun': 'Tingkat',
    'ui.grade': 'Kelas',
    'ui.rank': 'Pangkat',
    'ui.position': 'Posisi',
    'ui.location': 'Lokasi',
    'ui.place': 'Tempat',
    'ui.site': 'Situs',
    'ui.area': 'Wewengkon',
    'ui.region': 'Wewengkon',
    'ui.zone': 'Zona',
    'ui.district': 'Kacamatan',
    'ui.neighborhood': 'Lingkungan',
    'ui.community': 'Komunitas',
    'ui.society': 'Masarakat',
    'ui.people': 'Jalma',
    'ui.person': 'Jalma',
    'ui.individual': 'Individu',
    'ui.citizen': 'Warga',
    'ui.resident': 'Penduduk',
    'ui.inhabitant': 'Pangeusi',
    'ui.population': 'Populasi',
    'ui.demographic': 'Démografis',
    'ui.statistics': 'Statistik',
    'ui.data_noun': 'Data',
    'ui.information_noun': 'Informasi',
    'ui.news': 'Béja',
    'ui.announcement': 'Pengumuman',
    'ui.notice': 'Béwara',
    'ui.alert_noun': 'Waspada',
    'ui.warning_noun': 'Peringatan',
    'ui.caution': 'Ati-ati',
    'ui.danger_noun': 'Bahaya',
    'ui.emergency': 'Darurat',
    'ui.crisis': 'Krisis',
    'ui.problem': 'Masalah',
    'ui.issue': 'Masalah',
    'ui.difficulty': 'Kasusahan',
    'ui.challenge': 'Tantangan',
    'ui.obstacle': 'Halangan',
    'ui.barrier': 'Panghalang',
    'ui.limitation': 'Watesan',
    'ui.restriction': 'Watesan',
    'ui.constraint': 'Konstrain',
    'ui.requirement': 'Sarat',
    'ui.condition': 'Kaayaan',
    'ui.situation': 'Situasi',
    'ui.circumstance': 'Kaayaan',
    'ui.context': 'Kontéks',
    'ui.environment': 'Lingkungan',
    'ui.setting': 'Setélan',
    'ui.background': 'Latar',
    'ui.foreground': 'Payun',
    'ui.surface': 'Permukaan',
    'ui.interior': 'Jero',
    'ui.exterior': 'Luar',
    'ui.boundary': 'Wates',
    'ui.border': 'Wates',
    'ui.edge': 'Ujung',
    'ui.margin': 'Margin',
    'ui.padding': 'Padding',
    'ui.spacing': 'Spasi',
    'ui.gap': 'Celah',
    'ui.distance': 'Jarak',
    'ui.length': 'Panjang',
    'ui.width': 'Lebar',
    'ui.height': 'Jangkungna',
    'ui.depth': 'Jero',
    'ui.thickness': 'Kandel',
    'ui.radius': 'Radius',
    'ui.diameter': 'Diaméter',
    'ui.circumference': 'Keliling',
    'ui.perimeter': 'Keliling',
    'ui.area_measurement': 'Luas',
    'ui.capacity_measurement': 'Kapasitas',
    'ui.weight': 'Beurat',
    'ui.mass': 'Massa',
    'ui.density': 'Kapadetan',
    'ui.pressure': 'Tekanan',
    'ui.temperature': 'Suhu',
    'ui.humidity': 'Kalembaban',
    'ui.moisture': 'Kalembaban',
    'ui.dryness': 'Kageringan',
    'ui.wetness': 'Kabasahan',
    'ui.speed': 'Laju',
    'ui.velocity': 'Laju',
    'ui.acceleration': 'Akselerasi',
    'ui.deceleration': 'Deselerasi',
    'ui.momentum': 'Momentum',
    'ui.inertia': 'Inersia',
    'ui.friction': 'Gesekan',
    'ui.resistance': 'Résistansi',
    'ui.conductivity': 'Konduktivitas',
    'ui.insulation': 'Isolasi',
    'ui.transmission': 'Transmisi',
    'ui.reception': 'Penerimaan',
    'ui.signal': 'Sinyal',
    'ui.frequency_noun': 'Frékuénsi',
    'ui.wavelength': 'Panjang gelombang',
    'ui.amplitude': 'Amplitudo',
    'ui.phase': 'Fase',
    'ui.cycle': 'Siklus',
    'ui.period': 'Période',
    'ui.interval': 'Interval',
    'ui.sequence': 'Urutan',
    'ui.series': 'Séri',
    'ui.set': 'Set',
    'ui.group': 'Grup',
    'ui.collection': 'Koléksi',
    'ui.grid': 'Rarangke',
    'ui.list': 'Urutan',
    
    // Regulations Page
    'regulations.title': 'Peraturan Désa',
    'regulations.subtitle': 'Kumpulan peraturan désa anu berlaku di wilayah Kabupaten Bandung Barat',
    'regulations.search_placeholder': 'Pilari aturan desa',
    'regulations.all_years': 'Sadaya Tahun',
    'regulations.download_count': 'kali diunduh',
    'regulations.no_results': 'Tidak ada peraturan yang ditemukan',
    'regulations.download_button': 'Unduh',
    'regulations.showing_results': 'Nampilkeun {count} aturan',
    'regulations.category_peraturan': 'Aturan',
    'ui.list_noun': 'Daptar',
    'ui.array': 'Array',
    'ui.table_noun': 'Tabel',
    'ui.database': 'Basis data',
    'ui.entry': 'Éntri',
    'ui.item': 'Item',
    'ui.element': 'Elemen',
    'ui.component': 'Komponén',
    'ui.part': 'Bagian',
    'ui.section': 'Bagian',
    'ui.chapter': 'Bab',
    'ui.paragraph': 'Paragraf',
    'ui.sentence': 'Kalimah',
    'ui.word': 'Kecap',
    'ui.letter_alphabet': 'Hurup',
    'ui.character': 'Karakter',
    'ui.symbol_noun': 'Simbol',
    'ui.sign_noun': 'Tanda',
    'ui.mark': 'Tanda',
    'ui.indicator': 'Indikator',
    'ui.pointer': 'Penunjuk',
    'ui.cursor': 'Kursor',
    'ui.selection': 'Pilihan',
    'ui.choice': 'Pilihan',
    'ui.option': 'Pilihan',
    'ui.alternative': 'Alternatip',
    'ui.variant': 'Varian',
    'ui.version_noun': 'Vérsi',
    'ui.edition': 'Édisi',
    'ui.release': 'Rilis',
    'ui.update_noun': 'Update',
    'ui.upgrade_noun': 'Upgrade',
    'ui.patch': 'Patch',
    'ui.fix': 'Perbaikan',
    'ui.repair': 'Perbaikan',
    'ui.maintenance_noun': 'Pangropéa',
    'ui.service_noun': 'Palayanan',
    'ui.support_noun': 'Dukungan',
    'ui.assistance_noun': 'Bantuan',
    'ui.guidance': 'Bimbingan',
    'ui.instruction': 'Instruksi',
    'ui.direction': 'Arah',
    'ui.command': 'Paréntah',
    'ui.order': 'Paréntah',
    'ui.request': 'Pamundut',
    'ui.demand': 'Paménta',
    'ui.requirement_noun': 'Sarat',
    'ui.specification': 'Spésifikasi',
    'ui.standard_noun': 'Standar',
    'ui.guideline': 'Pedoman',
    'ui.rule': 'Aturan',
    'ui.regulation': 'Peraturan',
    'ui.law': 'Hukum',
    'ui.policy': 'Kabijakan',
    'ui.principle': 'Prinsip',
    'ui.concept': 'Konsép',
    'ui.idea': 'Idé',
    'ui.thought': 'Pikiran',
    'ui.opinion': 'Pendapat',
    'ui.view': 'Pandangan',
    'ui.perspective': 'Perspéktip',
    'ui.angle': 'Sudut',
    'ui.aspect': 'Aspék',
    'ui.factor': 'Faktor',
    'ui.element_noun': 'Elemen',
    'ui.ingredient': 'Bahan',
    'ui.material': 'Bahan',
    'ui.substance': 'Zat',
    'ui.matter': 'Materi',
    'ui.object': 'Objék',
    'ui.thing': 'Hal',
    'ui.stuff': 'Barang',
    'ui.item_noun': 'Barang',
    'ui.product': 'Produk',
    'ui.goods': 'Barang',
    'ui.merchandise': 'Dagangan',
    'ui.commodity': 'Komoditas',
    'ui.resource': 'Sumber daya',
    'ui.asset': 'Aset',
    'ui.property_noun': 'Harta',
    'ui.possession': 'Milik',
    'ui.ownership': 'Kapamilikan',
    'ui.privilege': 'Hak istimewa',
    'ui.authority': 'Otoritas',
    'ui.responsibility': 'Tanggung jawab',
    'ui.duty': 'Tugas',
    'ui.obligation': 'Kawajiban',
    'ui.commitment': 'Komitmen',
    'ui.promise': 'Janji',
    'ui.pledge': 'Janji',
    'ui.vow': 'Sumpah',
    'ui.oath': 'Sumpah',
    'ui.declaration': 'Deklarasi',
    'ui.statement': 'Pernyataan',
    'ui.claim': 'Klaim',
    'ui.assertion': 'Pernyataan',
    'ui.argument': 'Argumen',
    'ui.reasoning': 'Penalaran',
    'ui.logic': 'Logika',
    'ui.rationale': 'Alasan',
    'ui.justification': 'Justifikasi',
    'ui.explanation': 'Penjelasan',
    'ui.clarification': 'Klarifikasi',
    'ui.interpretation': 'Interpretasi',
    'ui.translation': 'Tarjamahan',
    'ui.conversion': 'Konvérsi',
    'ui.transformation': 'Transformasi',
    'ui.change_noun': 'Parobahan',
    'ui.modification': 'Modifikasi',
    'ui.adjustment': 'Panyesuaian',
    'ui.adaptation': 'Adaptasi',
    'ui.evolution': 'Évolusi',
    'ui.development_noun': 'Pangwangunan',
    'ui.progress': 'Kamajuan',
    'ui.advancement': 'Kamajuan',
    'ui.improvement_noun': 'Perbaikan',
    'ui.enhancement': 'Peningkatan',
    'ui.optimization': 'Optimisasi',
    'ui.efficiency': 'Efisiensi',
    'ui.effectiveness': 'Efektivitas',
    'ui.productivity': 'Produktivitas',
    'ui.performance': 'Kinerja',
    'ui.quality_noun': 'Kualitas',
    'ui.excellence': 'Kaunggulan',
    'ui.superiority': 'Kaunggulan',
    'ui.inferiority': 'Kekurangan',
    'ui.deficiency': 'Kekurangan',
    'ui.shortage': 'Kekurangan',
    'ui.lack': 'Kurang',
    'ui.absence': 'Henteuna',
    'ui.presence': 'Ayana',
    'ui.existence': 'Ayana',
    'ui.reality': 'Kanyataan',
    'ui.truth': 'Kaleresan',
    'ui.fact': 'Kanyataan',
    'ui.evidence': 'Bukti',
    'ui.proof': 'Bukti',
    'ui.demonstration': 'Demonstrasi',
    'ui.example': 'Conto',
    'ui.instance': 'Conto',
    'ui.case': 'Kasus',
    'ui.scenario': 'Skenario',
    'ui.situation_noun': 'Situasi',
    'ui.condition_noun': 'Kaayaan',
    'ui.state': 'Kaayaan',
    'ui.phase_noun': 'Fase',
    'ui.stage': 'Tahap',
    'ui.step': 'Léngkah',
    'ui.action': 'Aksi',
    'ui.activity': 'Kagiatan',
    'ui.task': 'Tugas',
    'ui.job': 'Gawéan',
    'ui.work_noun': 'Gawé',
    'ui.labor': 'Tanaga gawé',
    'ui.effort_noun': 'Usaha',
    'ui.energy_effort': 'Énergi',
    'ui.power_effort': 'Kakuatan',
    'ui.strength_noun': 'Kakuatan',
    'ui.force_noun': 'Kakuatan',
    'ui.pressure_noun': 'Tekanan',
    'ui.stress_noun': 'Stres',
    'ui.tension': 'Tegangan',
    'ui.strain': 'Tegangan',
    'ui.load': 'Beban',
    'ui.burden': 'Beban',
    'ui.weight_noun': 'Beurat',
    'ui.mass_noun': 'Massa',
    'ui.volume_noun': 'Volume',
    'ui.capacity_noun': 'Kapasitas',
    'ui.space': 'Rohangan',
    'ui.room_noun': 'Rohangan',
    'ui.area_noun': 'Wewengkon',
    'ui.territory': 'Wilayah',
    'ui.domain': 'Domain',
    'ui.field': 'Widang',
    'ui.scope': 'Ruang lingkup',
    'ui.range_noun': 'Rentang',
    'ui.extent': 'Luasna',
    'ui.limit': 'Wates',
    'ui.boundary_noun': 'Wates',
    'ui.border_noun': 'Wates',
    'ui.frontier': 'Wates',
    'ui.threshold': 'Ambang',
    'ui.minimum_noun': 'Minimum',
    'ui.maximum_noun': 'Maksimum',
    'ui.peak': 'Puncak',
    'ui.summit': 'Puncak',
    'ui.top_noun': 'Luhur',
    'ui.bottom_noun': 'Handap',
    'ui.base': 'Dasar',
    'ui.foundation': 'Pondasi',
    'ui.ground_noun': 'Taneuh',
    'ui.floor_noun': 'Lantai',
    'ui.surface_noun': 'Permukaan',
    'ui.layer': 'Lapisan',
    'ui.level_noun': 'Tingkat',
    'ui.tier': 'Tingkat',
    'ui.rank_noun': 'Pangkat',
    'ui.grade_noun': 'Kelas',
    'ui.class_noun': 'Kelas',
    'ui.category': 'Kategori',
    'ui.type': 'Jenis',
    'ui.variety': 'Variétas',
    'ui.diversity': 'Karagaman',
    'ui.difference': 'Bédana',
    'ui.distinction': 'Bédana',
    'ui.comparison': 'Perbandingan',
    'ui.similarity': 'Kasaruaan',
    'ui.resemblance': 'Kasaruaan',
    'ui.likeness': 'Kasaruaan',
    'ui.match': 'Cocog',
    'ui.fit': 'Pas',
    'ui.suitability': 'Kasesuaian',
    'ui.compatibility': 'Kompatibilitas',
    'ui.harmony': 'Harmoni',
    'ui.equilibrium': 'Kasaimbangan',
    'ui.stability': 'Stabilitas',
    'ui.consistency': 'Konsistensi',
    'ui.reliability': 'Kaandalan',
    'ui.dependability': 'Kaandalan',
    'ui.trustworthiness': 'Kapercayaan',
    'ui.credibility': 'Kredibilitas',
    'ui.reputation': 'Reputasi',
    'ui.impression': 'Kesan',
    'ui.perception': 'Persépsi',
    'ui.understanding': 'Pamahaman',
    'ui.comprehension': 'Pamahaman',
    'ui.awareness': 'Kasadaran',
    'ui.consciousness': 'Kasadaran',
    'ui.recognition_noun': 'Pangakuan',
    'ui.acknowledgment_noun': 'Pangakuan',
    'ui.acceptance_noun': 'Penerimaan',
    'ui.approval_noun': 'Persetujuan',
    'ui.consent': 'Idin',
    'ui.agreement_noun': 'Kasepakatan',
    'ui.accord': 'Kasepakatan',
    'ui.harmony_noun': 'Harmoni',
    'ui.unity': 'Persatuan',
    'ui.union': 'Persatuan',
    'ui.alliance': 'Aliansi',
    'ui.partnership': 'Kemitraan',
    'ui.collaboration': 'Kolaborasi',
    'ui.cooperation': 'Gawé babarengan',
    'ui.teamwork': 'Gawé tim',
    'ui.coordination': 'Koordinasi',
    'ui.organization': 'Organisasi',
    'ui.management': 'Manajemén',
    'ui.administration': 'Administrasi',
    'ui.governance': 'Pamaréntahan',
    'ui.leadership': 'Kapamimpinan',
    'ui.guidance_noun': 'Bimbingan',
    'ui.direction_noun': 'Arah',
    'ui.supervision': 'Pangawasan',
    'ui.oversight': 'Pangawasan',
    'ui.control': 'Kontrol',
    'ui.regulation_noun': 'Peraturan',
    'ui.rule_noun': 'Aturan',
    'ui.law_noun': 'Hukum',
    'ui.legislation': 'Undang-undang',
    'ui.statute': 'Undang-undang',
    'ui.ordinance': 'Perda',
    'ui.decree': 'Dekrit',
    'ui.order_noun': 'Paréntah',
    'ui.command_noun': 'Paréntah',
    'ui.instruction_noun': 'Instruksi',
    'ui.guideline_noun': 'Pedoman',
    'ui.procedure_noun': 'Prosedur',
    'ui.protocol': 'Protokol',
    'ui.standard_procedure': 'Prosedur standar',
    'ui.best_practice': 'Prakték panghadéna',
    'ui.recommendation': 'Rekomendasi',
    'ui.suggestion': 'Saran',
    'ui.advice': 'Naséhat',
    'ui.tip': 'Tips',
    'ui.hint': 'Petunjuk',
    'ui.clue': 'Petunjuk',
    'ui.indication': 'Indikasi',
    'ui.sign_indication': 'Tanda',
    'ui.symptom': 'Gejala',
    'ui.signal_noun': 'Sinyal',
    'ui.warning_signal': 'Sinyal peringatan',
    'ui.alarm': 'Alarm',
    'ui.alert_signal': 'Sinyal waspada',
    'ui.notification_noun': 'Béwara',
    'ui.announcement_noun': 'Pengumuman',
    'ui.declaration_noun': 'Deklarasi',
    'ui.proclamation': 'Proklamasi',
    'ui.statement_noun': 'Pernyataan',
    'ui.report_noun': 'Laporan',
    'ui.record_noun': 'Catetan',
    'ui.log': 'Log',
    'ui.journal': 'Jurnal',
    'ui.diary': 'Buku harian',
    'ui.chronicle': 'Kronik',
    'ui.history_noun': 'Sajarah',
    'ui.archive': 'Arsip',
    'ui.collection_noun': 'Koléksi',
    'ui.library_noun': 'Perpustakaan',
    'ui.repository': 'Repositori',
    'ui.storage': 'Panyimpenan',
    'ui.warehouse': 'Gudang',
    'ui.depot': 'Depot',
    'ui.facility': 'Fasilitas',
    'ui.infrastructure': 'Infrastruktur',
    'ui.equipment': 'Peralatan',
    'ui.tool': 'Alat',
    'ui.instrument': 'Instrumén',
    'ui.device': 'Alat',
    'ui.machine': 'Mesin',
    'ui.apparatus': 'Aparatur',
    'ui.mechanism_noun': 'Mékanisme',
    'ui.system_noun': 'Sistem',
    'ui.network': 'Jaringan',
    'ui.connection': 'Sambungan',
    'ui.link': 'Tautan',
    'ui.relationship': 'Hubungan',
    'ui.association': 'Asosiasi',
    'ui.affiliation': 'Afiliasi',
    'ui.membership': 'Keanggotaan',
    'ui.participation': 'Partisipasi',
    'ui.involvement': 'Keterlibatan',
    'ui.engagement': 'Keterlibatan',
    'ui.interaction': 'Interaksi',
    'ui.communication_noun': 'Komunikasi',
    'ui.correspondence': 'Korespondensi',
    'ui.exchange': 'Pertukaran',
    'ui.transaction': 'Transaksi',
    'ui.deal_noun': 'Kasepakatan',
    'ui.business': 'Bisnis',
    'ui.commerce': 'Perdagangan',
    'ui.trade': 'Dagang',
    'ui.market_noun': 'Pasar',
    'ui.economy': 'Ékonomi',
    'ui.finance': 'Keuangan',
    'ui.money': 'Duit',
    'ui.currency': 'Mata uang',
    'ui.cash': 'Tunai',
    'ui.credit_money': 'Krédit',
    'ui.debit_money': 'Débit',
    'ui.account_money': 'Rekening',
    'ui.balance_money': 'Saldo',
    'ui.fund': 'Dana',
    'ui.capital': 'Modal',
    'ui.investment_noun': 'Investasi',
    'ui.asset_noun': 'Aset',
    'ui.liability': 'Kewajiban',
    'ui.equity': 'Ekuitas',
    'ui.stock': 'Saham',
    'ui.bond': 'Obligasi',
    'ui.portfolio': 'Portofolio',
    'ui.return': 'Hasil',
    'ui.yield': 'Hasil',
    'ui.dividend': 'Dividen',
    'ui.interest_money': 'Bunga',
    'ui.percentage_noun': 'Perséntase',
    'ui.ratio_noun': 'Rasio',
    'ui.proportion_noun': 'Proporsi',
    'ui.fraction': 'Pecahan',
    'ui.decimal': 'Desimal',
    'ui.integer': 'Bilangan bulat',
    'ui.number_noun': 'Angka',
    'ui.digit': 'Digit',
    'ui.figure': 'Angka',
    'ui.numeral': 'Angka',
    'ui.calculation': 'Itungan',
    'ui.computation': 'Komputasi',
    'ui.mathematics': 'Matematika',
    'ui.arithmetic': 'Aritmatika',
    'ui.algebra': 'Aljabar',
    'ui.geometry': 'Géométri',
    'ui.trigonometry': 'Trigonométri',
    'ui.calculus': 'Kalkulus',
    'ui.statistics_noun': 'Statistik',
    'ui.probability_noun': 'Probabilitas',
    'ui.logic_noun': 'Logika',
    'ui.algorithm': 'Algoritma',
    'ui.formula': 'Rumus',
    'ui.equation': 'Persamaan',
    'ui.expression': 'Éksprési',
    'ui.variable': 'Variabel',
    'ui.constant': 'Konstanta',
    'ui.parameter': 'Paramétér',
    'ui.argument_math': 'Argumén',
    'ui.function_math': 'Fungsi',
    'ui.operation_math': 'Operasi',
    'ui.addition': 'Penjumlahan',
    'ui.subtraction': 'Pangurangan',
    'ui.multiplication': 'Perkalian',
    'ui.division': 'Pembagian',
    'ui.exponentiation': 'Pangkat',
    'ui.root': 'Akar',
    'ui.logarithm': 'Logaritma',
    'ui.sine': 'Sinus',
    'ui.cosine': 'Kosinus',
    'ui.tangent': 'Tangen',
    'ui.derivative': 'Turunan',
    'ui.integral': 'Integral',
    'ui.infinity': 'Takterhingga',
    'ui.zero': 'Nol',
    'ui.one': 'Hiji',
    'ui.two': 'Dua',
    'ui.three': 'Tilu',
    'ui.four': 'Opat',
    'ui.five': 'Lima',
    'ui.six': 'Genep',
    'ui.seven': 'Tujuh',
    'ui.eight': 'Dalapan',
    'ui.nine': 'Salapan',
    'ui.ten': 'Sapuluh',
    'ui.hundred': 'Saratus',
    'ui.thousand': 'Sarébu',
    'ui.million': 'Sajuta',
    'ui.billion': 'Samilyar',
    'ui.trillion': 'Satriliun',
    'ui.button': 'Tombol',
    'ui.p': 'Paragraf',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('id');

  const t = (key: string): string => {
    const translation = translations[language][key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key} in language: ${language}`);
      return key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}